In [1]:
import optuna 
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import pandas as pd

url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

df = pd.read_csv(url, names=columns)
df.head()

c:\Users\husna\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
import numpy as np

# replace zero values with mean of respective column 
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0,np.nan)

# impute the missing values with mean of respective column 
df.fillna(df.mean(), inplace=True)

print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
X = df.drop('Outcome', axis=1)
y = df['Outcome']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(f"Training set shape: {X_train.shape}")
print(f"Testing set shape: {X_test.shape}")

Training set shape: (537, 8)
Testing set shape: (231, 8)

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# define objective function 
def objective(trial):
    n_estimators = trial.suggest_int('n_estimators',50,200)
    max_depth = trial.suggest_int('max_depth',3,20)

    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    score = cross_val_score(model, X_train, y_train, cv=3,scoring='accuracy').mean()
    return score

In [9]:
study = optuna.create_study(direction='maximize',sampler=optuna.samplers.TPESampler())
study.optimize(objective,n_trials=50)

[I 2026-09-28 23:13:30,055] A new study created in memory with name: no-name-a14f907c-67e7-40ff-baab-88a59f89e412
[I 2026-09-28 23:13:31,515] Trial 0 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 131, 'max_depth': 13}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-09-28 23:13:33,140] Trial 1 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 153, 'max_depth': 20}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-09-28 23:13:36,220] Trial 2 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 154, 'max_depth': 7}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-09-28 23:13:37,643] Trial 3 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 82, 'max_depth': 11}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-09-28 23:13:38,694] Trial 4 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 82, 'max_depth': 11}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-09-28 23:13:39,772] Trial 5 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 62, 'max_depth': 4}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-09-28 23:13:40,392] Trial 6 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 52, 'max_depth': 19}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-09-28 23:13:44,135] Trial 7 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 165, 'max_depth': 8}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-09-28 23:13:45,394] Trial 8 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 56, 'max_depth': 20}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-09-28 23:13:46,792] Trial 9 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 108, 'max_depth': 19}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-09-28 23:13:50,143] Trial 10 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 199, 'max_depth': 8}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-09-28 23:13:52,253] Trial 11 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 156, 'max_depth': 14}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-09-28 23:13:53,819] Trial 12 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 148, 'max_depth': 3}. Best is trial 2 with value: 0.7765363128491619.
[I 2026-09-28 23:13:55,551] Trial 13 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 123, 'max_depth': 16}. Best is trial 13 with value: 0.7783985102420856.
[I 2026-09-28 23:13:57,210] Trial 14 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 114, 'max_depth': 6}. Best is trial 13 with value: 0.7783985102420856.
[I 2026-09-28 23:13:59,862] Trial 15 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 181, 'max_depth': 16}. Best is trial 13 with value: 0.7783985102420856.
[I 2026-09-28 23:14:03,425] Trial 16 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 192, 'max_depth': 17}. Best is trial 13 with value: 0.7783985102420856.
[I 2026-09-28 23:14:04,805] Trial 17 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 123, 'max_depth': 17}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:05,909] Trial 18 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 94, 'max_depth': 16}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:07,581] Trial 19 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 129, 'max_depth': 15}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:09,735] Trial 20 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 165, 'max_depth': 11}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:11,599] Trial 21 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 140, 'max_depth': 18}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:12,591] Trial 22 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 63, 'max_depth': 15}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:15,597] Trial 23 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 193, 'max_depth': 14}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:18,484] Trial 24 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 174, 'max_depth': 19}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:19,651] Trial 25 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 107, 'max_depth': 13}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:21,635] Trial 26 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 126, 'max_depth': 19}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:23,857] Trial 27 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 153, 'max_depth': 16}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:24,981] Trial 28 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 96, 'max_depth': 19}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:26,273] Trial 29 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 139, 'max_depth': 9}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:27,796] Trial 30 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 171, 'max_depth': 16}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:29,793] Trial 31 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 174, 'max_depth': 13}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:31,931] Trial 32 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 167, 'max_depth': 16}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:33,247] Trial 33 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 114, 'max_depth': 17}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:35,151] Trial 34 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 144, 'max_depth': 15}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:38,460] Trial 35 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 157, 'max_depth': 18}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:39,445] Trial 36 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 76, 'max_depth': 18}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:41,270] Trial 37 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 119, 'max_depth': 14}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:41,821] Trial 38 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 56, 'max_depth': 10}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:43,202] Trial 39 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 138, 'max_depth': 12}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:44,150] Trial 40 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 98, 'max_depth': 7}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:46,012] Trial 41 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 183, 'max_depth': 16}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:47,690] Trial 42 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 187, 'max_depth': 11}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:49,336] Trial 43 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 167, 'max_depth': 14}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:51,042] Trial 44 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 179, 'max_depth': 17}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:52,431] Trial 45 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 137, 'max_depth': 16}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:53,728] Trial 46 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 146, 'max_depth': 20}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:55,120] Trial 47 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 153, 'max_depth': 16}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:56,829] Trial 48 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 149, 'max_depth': 13}. Best is trial 17 with value: 0.7802607076350093.
[I 2026-09-28 23:14:58,006] Trial 49 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 130, 'max_depth': 20}. Best is trial 17 with value: 0.7802607076350093.

In [10]:
# print the best result 
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 123, 'max_depth': 17}

In [11]:
from sklearn.metrics import accuracy_score

best_model = RandomForestClassifier(**study.best_trial.params,random_state=42)
best_model.fit(X_train,y_train)

y_pred = best_model.predict(X_test)

test_accuracy = accuracy_score(y_test,y_pred)
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

## samplers in optuna

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [13]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2026-09-28 23:22:29,328] A new study created in memory with name: no-name-9ccb8ca1-7303-4dcf-bfc5-be6a8415baea
[I 2026-09-28 23:22:30,624] Trial 0 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 74, 'max_depth': 8}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-09-28 23:22:31,348] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 53, 'max_depth': 11}. Best is trial 0 with value: 0.7728119180633147.
[I 2026-09-28 23:22:32,655] Trial 2 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 71, 'max_depth': 19}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:22:35,401] Trial 3 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 154, 'max_depth': 12}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:22:36,541] Trial 4 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 88, 'max_depth': 16}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:22:38,276] Trial 5 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 144, 'max_depth': 4}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:22:39,110] Trial 6 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 90, 'max_depth': 3}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:22:40,628] Trial 7 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 161, 'max_depth': 4}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:22:44,950] Trial 8 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 185, 'max_depth': 8}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:22:46,679] Trial 9 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 131, 'max_depth': 9}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:22:48,705] Trial 10 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 101, 'max_depth': 11}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:22:51,055] Trial 11 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 140, 'max_depth': 4}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:22:52,534] Trial 12 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 144, 'max_depth': 19}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:22:54,108] Trial 13 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 129, 'max_depth': 10}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:22:54,859] Trial 14 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 52, 'max_depth': 16}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:22:55,942] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 80, 'max_depth': 13}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:22:57,255] Trial 16 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 106, 'max_depth': 15}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:00,724] Trial 17 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 195, 'max_depth': 14}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:02,720] Trial 18 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 135, 'max_depth': 12}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:05,812] Trial 19 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 166, 'max_depth': 17}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:06,972] Trial 20 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 58, 'max_depth': 12}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:09,108] Trial 21 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 174, 'max_depth': 10}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:12,160] Trial 22 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 154, 'max_depth': 5}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:13,957] Trial 23 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 138, 'max_depth': 6}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:16,585] Trial 24 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 168, 'max_depth': 20}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:18,657] Trial 25 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 141, 'max_depth': 16}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:19,817] Trial 26 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 76, 'max_depth': 9}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:21,077] Trial 27 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 114, 'max_depth': 10}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:22,941] Trial 28 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 116, 'max_depth': 6}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:25,596] Trial 29 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 139, 'max_depth': 14}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:27,696] Trial 30 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 127, 'max_depth': 13}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:28,682] Trial 31 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 97, 'max_depth': 3}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:30,035] Trial 32 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 115, 'max_depth': 13}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:31,204] Trial 33 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 11}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:32,479] Trial 34 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 103, 'max_depth': 12}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:33,898] Trial 35 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 92, 'max_depth': 12}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:34,980] Trial 36 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 91, 'max_depth': 4}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:36,534] Trial 37 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 137, 'max_depth': 14}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:38,219] Trial 38 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 132, 'max_depth': 10}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:39,565] Trial 39 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 109, 'max_depth': 6}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:40,962] Trial 40 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 129, 'max_depth': 3}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:42,385] Trial 41 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 147, 'max_depth': 7}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:44,505] Trial 42 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 125, 'max_depth': 17}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:46,246] Trial 43 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 64, 'max_depth': 15}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:49,132] Trial 44 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 185, 'max_depth': 11}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:50,974] Trial 45 finished with value: 0.7746741154562383 and parameters: {'n_estimators': 171, 'max_depth': 7}. Best is trial 2 with value: 0.7783985102420857.
[I 2026-09-28 23:23:53,002] Trial 46 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 129, 'max_depth': 17}. Best is trial 46 with value: 0.7802607076350093.
[I 2026-09-28 23:23:55,485] Trial 47 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 198, 'max_depth': 20}. Best is trial 46 with value: 0.7802607076350093.
[I 2026-09-28 23:23:56,407] Trial 48 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 57, 'max_depth': 5}. Best is trial 46 with value: 0.7802607076350093.
[I 2026-09-28 23:23:58,374] Trial 49 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 162, 'max_depth': 6}. Best is trial 46 with value: 0.7802607076350093.

In [14]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 129, 'max_depth': 17}

In [15]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

In [16]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [17]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-09-28 23:24:01,281] A new study created in memory with name: no-name-8daa4260-9ba4-494d-9b90-47472f15908e
[I 2026-09-28 23:24:03,155] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-09-28 23:24:05,560] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2026-09-28 23:24:06,276] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-28 23:24:08,017] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-28 23:24:09,274] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-28 23:24:09,869] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-28 23:24:11,967] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-28 23:24:13,809] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-28 23:24:18,087] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-28 23:24:21,203] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-28 23:24:24,256] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-28 23:24:28,321] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-28 23:24:30,612] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2026-09-28 23:24:32,189] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-09-28 23:24:33,282] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2026-09-28 23:24:33,765] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [18]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [19]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

## optuna visualization

In [20]:
from optuna.visualization import plot_optimization_history,plot_parallel_coordinate,plot_slice,plot_contour,plot_param_importances

In [21]:
plot_optimization_history(study).show()

In [22]:
plot_parallel_coordinate(study).show()

In [23]:
plot_slice(study).show()

In [24]:
plot_contour(study).show()

In [25]:
plot_param_importances(study).show()

## optimizing multiple ml models

In [26]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [27]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [28]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2026-09-28 23:28:22,532] A new study created in memory with name: no-name-77753c40-6baa-4cce-8350-86756f501ec9
[I 2026-09-28 23:28:22,612] Trial 0 finished with value: 0.7094972067039107 and parameters: {'classifier': 'SVM', 'C': 3.7587178952098568, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 0 with value: 0.7094972067039107.
[I 2026-09-28 23:28:24,334] Trial 1 finished with value: 0.7783985102420856 and parameters: {'classifier': 'RandomForest', 'n_estimators': 134, 'max_depth': 11, 'min_samples_split': 8, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 1 with value: 0.7783985102420856.
[I 2026-09-28 23:28:28,803] Trial 2 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 300, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 1 with value: 0.7783985102420856.
[I 2026-09-28 23:28:32,141] Trial 3 finished with value: 0.7541899441340782 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 214, 'learning_rate': 0.09478155256341397, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 6}. Best is trial 1 with value: 0.7783985102420856.
[I 2026-09-28 23:28:32,332] Trial 4 finished with value: 0.7579143389199254 and parameters: {'classifier': 'SVM', 'C': 0.3073391333709889, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 1 with value: 0.7783985102420856.
[I 2026-09-28 23:28:35,014] Trial 5 finished with value: 0.7523277467411545 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 86, 'learning_rate': 0.290153399978751, 'max_depth': 7, 'min_samples_split': 3, 'min_samples_leaf': 3}. Best is trial 1 with value: 0.7783985102420856.
[I 2026-09-28 23:28:35,073] Trial 6 finished with value: 0.7392923649906891 and parameters: {'classifier': 'SVM', 'C': 0.627225694727542, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 1 with value: 0.7783985102420856.
[I 2026-09-28 23:28:35,150] Trial 7 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 2.121090205868186, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 1 with value: 0.7783985102420856.
[I 2026-09-28 23:28:35,204] Trial 8 finished with value: 0.7001862197392924 and parameters: {'classifier': 'SVM', 'C': 7.166282743801425, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 1 with value: 0.7783985102420856.
[I 2026-09-28 23:28:35,274] Trial 9 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.16302063369228387, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 9 with value: 0.7877094972067038.
[I 2026-09-28 23:28:37,515] Trial 10 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 197, 'max_depth': 19, 'min_samples_split': 10, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 9 with value: 0.7877094972067038.
[I 2026-09-28 23:28:38,136] Trial 11 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 63, 'max_depth': 13, 'min_samples_split': 10, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 9 with value: 0.7877094972067038.
[I 2026-09-28 23:28:39,555] Trial 12 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 139, 'max_depth': 4, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 9 with value: 0.7877094972067038.
[I 2026-09-28 23:28:43,935] Trial 13 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 296, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 9 with value: 0.7877094972067038.
[I 2026-09-28 23:28:47,821] Trial 14 finished with value: 0.7709497206703911 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 166, 'learning_rate': 0.01177253303391432, 'max_depth': 13, 'min_samples_split': 2, 'min_samples_leaf': 7}. Best is trial 9 with value: 0.7877094972067038.
[I 2026-09-28 23:28:48,952] Trial 15 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 98.8523268741314, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 9 with value: 0.7877094972067038.
[I 2026-09-28 23:28:50,012] Trial 16 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 68.20253272280165, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 9 with value: 0.7877094972067038.
[I 2026-09-28 23:28:50,859] Trial 17 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 84.14904701168935, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 9 with value: 0.7877094972067038.
[I 2026-09-28 23:28:50,911] Trial 18 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11134488780924878, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:28:51,011] Trial 19 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10391664422330694, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:28:51,230] Trial 20 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13687483120149954, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:28:51,292] Trial 21 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1074171943289232, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:28:51,470] Trial 22 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.3383174020975556, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:28:51,842] Trial 23 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.24341172939735325, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:28:52,234] Trial 24 finished with value: 0.7299813780260708 and parameters: {'classifier': 'SVM', 'C': 0.9075002585044811, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:28:54,683] Trial 25 finished with value: 0.7653631284916201 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 248, 'learning_rate': 0.011752103828533334, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 1}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:28:54,824] Trial 26 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10389815200079783, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:28:54,934] Trial 27 finished with value: 0.7597765363128491 and parameters: {'classifier': 'SVM', 'C': 0.26846232823543087, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:28:55,016] Trial 28 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.635655892167327, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:28:55,071] Trial 29 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17960334821627036, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:00,832] Trial 30 finished with value: 0.7467411545623835 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 101, 'learning_rate': 0.04817262836978259, 'max_depth': 20, 'min_samples_split': 9, 'min_samples_leaf': 4}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:00,883] Trial 31 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10432603565641746, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:00,943] Trial 32 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17757293636532456, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:00,991] Trial 33 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.15537899666158056, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:01,045] Trial 34 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.46826454119092037, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:01,100] Trial 35 finished with value: 0.707635009310987 and parameters: {'classifier': 'SVM', 'C': 0.10148734005620436, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:01,180] Trial 36 finished with value: 0.7597765363128492 and parameters: {'classifier': 'SVM', 'C': 0.21133224996006478, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:12,051] Trial 37 finished with value: 0.7374301675977654 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 230, 'learning_rate': 0.0407728015419175, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:12,143] Trial 38 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 1.240320930421025, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:12,206] Trial 39 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.3618162919662937, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:16,519] Trial 40 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 258, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:16,586] Trial 41 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1442636957900535, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:16,650] Trial 42 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.158880054543746, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:16,706] Trial 43 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1565581387112742, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:16,763] Trial 44 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.23757835107698572, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:16,804] Trial 45 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.15158380787316356, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:19,730] Trial 46 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 172, 'max_depth': 15, 'min_samples_split': 8, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:19,791] Trial 47 finished with value: 0.7467411545623835 and parameters: {'classifier': 'SVM', 'C': 0.43000744565344823, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:21,310] Trial 48 finished with value: 0.750465549348231 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 116, 'learning_rate': 0.29501857551815575, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:21,372] Trial 49 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.29360361891907716, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:22,112] Trial 50 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 59, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:22,243] Trial 51 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13567811321917475, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:22,335] Trial 52 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1403200362896244, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:22,422] Trial 53 finished with value: 0.7132216014897579 and parameters: {'classifier': 'SVM', 'C': 0.1479854420780835, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:22,477] Trial 54 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.23299383454087483, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:22,536] Trial 55 finished with value: 0.7523277467411545 and parameters: {'classifier': 'SVM', 'C': 0.13638257753027913, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:22,660] Trial 56 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.5306302359980594, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:22,711] Trial 57 finished with value: 0.7132216014897579 and parameters: {'classifier': 'SVM', 'C': 6.5940206688095895, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:23,183] Trial 58 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 37.21918546295989, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:23,330] Trial 59 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.3359387330914141, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:23,438] Trial 60 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13305157329110404, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:23,544] Trial 61 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13898916996372274, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:23,677] Trial 62 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2080387946820932, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:23,850] Trial 63 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12889539906750783, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:24,073] Trial 64 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2034525648336878, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:24,188] Trial 65 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13035290835272487, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:30,341] Trial 66 finished with value: 0.7430167597765364 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 178, 'learning_rate': 0.10766428953548456, 'max_depth': 18, 'min_samples_split': 3, 'min_samples_leaf': 5}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:30,408] Trial 67 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10006840161475361, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:33,713] Trial 68 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 271, 'max_depth': 15, 'min_samples_split': 9, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:33,760] Trial 69 finished with value: 0.7281191806331471 and parameters: {'classifier': 'SVM', 'C': 0.28027480586531944, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:33,807] Trial 70 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.18712383297019555, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:33,856] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13117849164904938, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:33,907] Trial 72 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13118103006093382, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:33,961] Trial 73 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.18622857243387603, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:34,008] Trial 74 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.26058839883653306, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:34,082] Trial 75 finished with value: 0.7467411545623835 and parameters: {'classifier': 'SVM', 'C': 0.12610856764786513, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:34,126] Trial 76 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.173316250845072, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:34,164] Trial 77 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.34761135853514225, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:35,288] Trial 78 finished with value: 0.7728119180633147 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 145, 'learning_rate': 0.025132501609098988, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 9}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:35,350] Trial 79 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1048797051487069, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:35,413] Trial 80 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2212659130188435, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.
[I 2026-09-28 23:29:35,493] Trial 81 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12853495430343786, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 18 with value: 0.7895716945996275.

In [29]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.11134488780924878, 'kernel': 'linear', 'gamma': 'auto'}
Best trial accuracy: 0.7895716945996275

In [30]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,system_attrs_tpe:relative_params:0,state
0,0,0.709497,2026-09-28 23:28:22.535624,2026-09-28 23:28:22.612313,0 days 00:00:00.076689,3.758718,NaN,SVM,auto,sigmoid,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
1,1,0.778399,2026-09-28 23:28:22.615231,2026-09-28 23:28:24.334800,0 days 00:00:01.719569,NaN,False,RandomForest,NaN,NaN,NaN,11.0,9.0,8.0,134.0,NaN,COMPLETE
2,2,0.763501,2026-09-28 23:28:24.344256,2026-09-28 23:28:28.802482,0 days 00:00:04.458226,NaN,True,RandomForest,NaN,NaN,NaN,17.0,8.0,4.0,300.0,NaN,COMPLETE
3,3,0.754190,2026-09-28 23:28:28.805613,2026-09-28 23:28:32.141239,0 days 00:00:03.335626,NaN,NaN,GradientBoosting,NaN,NaN,0.094782,7.0,6.0,6.0,214.0,NaN,COMPLETE
4,4,0.757914,2026-09-28 23:28:32.141239,2026-09-28 23:28:32.332475,0 days 00:00:00.191236,0.307339,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,NaN,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.754190,2026-09-28 23:29:37.628531,2026-09-28 23:29:37.709114,0 days 00:00:00.080583,0.236431,NaN,SVM,scale,rbf,NaN,NaN,NaN,NaN,NaN,"{""classifier"": ""SVM""}",COMPLETE
96,96,0.744879,2026-09-28 23:29:37.710113,2026-09-28 23:29:43.208497,0 days 00:00:05.498384,NaN,NaN,GradientBoosting,NaN,NaN,0.137970,14.0,2.0,9.0,212.0,"{""classifier"": ""GradientBoosting""}",COMPLETE
97,97,0.787709,2026-09-28 23:29:43.209621,2026-09-28 23:29:43.322478,0 days 00:00:00.112857,0.155520,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,"{""classifier"": ""SVM""}",COMPLETE
98,98,0.785847,2026-09-28 23:29:43.322478,2026-09-28 23:29:43.434670,0 days 00:00:00.112192,0.202665,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,"{""classifier"": ""SVM""}",COMPLETE
99,99,0.785847,2026-09-28 23:29:43.436668,2026-09-28 23:29:43.520482,0 days 00:00:00.083814,0.299458,NaN,SVM,scale,linear,NaN,NaN,NaN,NaN,NaN,"{""classifier"": ""SVM""}",COMPLETE

In [31]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 79
RandomForest        11
GradientBoosting    10
Name: count, dtype: int64

In [32]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.753818
RandomForest        0.768410
SVM                 0.775806
Name: value, dtype: float64

In [33]:
# 1. Optimization History
plot_optimization_history(study).show()

In [34]:
# 3. Slice Plot
plot_slice(study).show()

In [35]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

In [37]:
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

# Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function for XGBoost
def objective(trial):
    # Hyperparameter search space
    param = {
        'verbosity': 0,
        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
        'booster': 'gbtree',
        'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'n_estimators': 300,
    }

    # Create DMatrix for XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    # Define a pruning callback based on evaluation metrics
    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list

    # Train the model
    bst = xgb.train(
        param,
        dtrain,
        num_boost_round=300,
        evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
        early_stopping_rounds=30,
        callbacks=[pruning_callback]
    )

    # Predict on the test set
    preds = bst.predict(dtest)
    best_preds = [int(np.argmax(line)) for line in preds]

    # Return accuracy as the objective value
    accuracy = accuracy_score(y_test, best_preds)
    return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

# Output the best trial
print(f"Best trial: {study.best_trial.params}")
print(f"Best accuracy: {study.best_value}")

[I 2026-09-28 23:31:10,179] A new study created in memory with name: no-name-af0ab865-0407-4116-83f9-e0cfd9cdb32d
c:\Users\husna\AppData\Local\Programs\Python\Python312\Lib\site-packages\optuna\integration\xgboost.py:14: FutureWarning: `optuna.integration.xgboost` has been deprecated in v4.9.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v4.9.0. Use `optuna_integration.xgboost` instead.
  optuna_warn(f"{msg} Use `optuna_integration.xgboost` instead.", FutureWarning)

[0]	train-mlogloss:0.80385	eval-mlogloss:0.79235
[1]	train-mlogloss:0.60696	eval-mlogloss:0.60813
[2]	train-mlogloss:0.46935	eval-mlogloss:0.46656
[3]	train-mlogloss:0.37026	eval-mlogloss:0.35909
[4]	train-mlogloss:0.29530	eval-mlogloss:0.27979
[5]	train-mlogloss:0.23737	eval-mlogloss:0.22798
[6]	train-mlogloss:0.19383	eval-mlogloss:0.18129
[7]	train-mlogloss:0.16057	eval-mlogloss:0.14432
[8]	train-mlogloss:0.13501	eval-mlogloss:0.11792
[9]	train-mlogloss:0.11378	eval-mlogloss:0.09837
[10]	train-mlogloss:0.09595	eval-mlogloss:0.08576
[11]	train-mlogloss:0.08241	eval-mlogloss:0.07406
[12]	train-mlogloss:0.07124	eval-mlogloss:0.06242
[13]	train-mlogloss:0.06333	eval-mlogloss:0.05258
[14]	train-mlogloss:0.05700	eval-mlogloss:0.04619
[15]	train-mlogloss:0.05177	eval-mlogloss:0.03831
[16]	train-mlogloss:0.04759	eval-mlogloss:0.03364
[17]	train-mlogloss:0.04356	eval-mlogloss:0.03023
[18]	train-mlogloss:0.04047	eval-mlogloss:0.02608
[19]	train-mlogloss:0.04026	eval-mlogloss:0.02625
[20]	train-mlogloss:0.03869	eval-mlogloss:0.02474
[21]	train-mlogloss:0.03749	eval-mlogloss:0.02304
[22]	train-mlogloss:0.03726	eval-mlogloss:0.02182
[23]	train-mlogloss:0.03567	eval-mlogloss:0.02210
[24]	train-mlogloss:0.03515	eval-mlogloss:0.02238
[25]	train-mlogloss:0.03453	eval-mlogloss:0.02220
[26]	train-mlogloss:0.03354	eval-mlogloss:0.02150
[27]	train-mlogloss:0.03320	eval-mlogloss:0.02015
[28]	train-mlogloss:0.03234	eval-mlogloss:0.01988
[29]	train-mlogloss:0.03174	eval-mlogloss:0.01942
[30]	train-mlogloss:0.03110	eval-mlogloss:0.01863
[31]	train-mlogloss:0.03094	eval-mlogloss:0.01861
[32]	train-mlogloss:0.03011	eval-mlogloss:0.01758
[33]	train-mlogloss:0.03027	eval-mlogloss:0.01743
[34]	train-mlogloss:0.02954	eval-mlogloss:0.01633
[35]	train-mlogloss:0.02905	eval-mlogloss:0.01630
[36]	train-mlogloss:0.02887	eval-mlogloss:0.01609
[37]	train-mlogloss:0.02869	eval-mlogloss:0.01573
[38]	train-mlogloss:0.02846	eval-mlogloss:0.01572
[39]	train-mlogloss:0.02796	eval-mlogloss:0.01554
[40]	train-mlogloss:0.02733	eval-mlogloss:0.01485
[41]	train-mlogloss:0.02664	eval-mlogloss:0.01433
[42]	train-mlogloss:0.02635	eval-mlogloss:0.01442
[43]	train-mlogloss:0.02638	eval-mlogloss:0.01506
[44]	train-mlogloss:0.02621	eval-mlogloss:0.01468
[45]	train-mlogloss:0.02575	eval-mlogloss:0.01416
[46]	train-mlogloss:0.02568	eval-mlogloss:0.01353
[47]	train-mlogloss:0.02548	eval-mlogloss:0.01366
[48]	train-mlogloss:0.02528	eval-mlogloss:0.01395
[49]	train-mlogloss:0.02497	eval-mlogloss:0.01344
[50]	train-mlogloss:0.02477	eval-mlogloss:0.01291
[51]	train-mlogloss:0.02447	eval-mlogloss:0.01239
[52]	train-mlogloss:0.02433	eval-mlogloss:0.01193
[53]	train-mlogloss:0.02407	eval-mlogloss:0.01193
[54]	train-mlogloss:0.02404	eval-mlogloss:0.01210
[55]	train-mlogloss:0.02370	eval-mlogloss:0.01205
[56]	train-mlogloss:0.02364	eval-mlogloss:0.01194
[57]	train-mlogloss:0.02334	eval-mlogloss:0.01198
[58]	train-mlogloss:0.02326	eval-mlogloss:0.01209
[59]	train-mlogloss:0.02325	eval-mlogloss:0.01248
[60]	train-mlogloss:0.02322	eval-mlogloss:0.01207
[61]	train-mlogloss:0.02293	eval-mlogloss:0.01232
[62]	train-mlogloss:0.02286	eval-mlogloss:0.01202
[63]	train-mlogloss:0.02274	eval-mlogloss:0.01175
[64]	train-mlogloss:0.02253	eval-mlogloss:0.01176
[65]	train-mlogloss:0.02244	eval-mlogloss:0.01165
[66]	train-mlogloss:0.02234	eval-mlogloss:0.01116
[67]	train-mlogloss:0.02233	eval-mlogloss:0.01100
[68]	train-mlogloss:0.02227	eval-mlogloss:0.01126
[69]	train-mlogloss:0.02212	eval-mlogloss:0.01099
[70]	train-mlogloss:0.02191	eval-mlogloss:0.01156
[71]	train-mlogloss:0.02183	eval-mlogloss:0.01194
[72]	train-mlogloss:0.02173	eval-mlogloss:0.01175
[73]	train-mlogloss:0.02167	eval-mlogloss:0.01176
[74]	train-mlogloss:0.02161	eval-mlogloss:0.01182
[75]	train-mlogloss:0.02167	eval-mlogloss:0.01150
[76]	train-mlogloss:0.02182	eval-mlogloss:0.01153
[77]	train-mlogloss:0.02188	eval-mlogloss:0.01137
[78]	train-mlogloss:0.02175	eval-mlogloss:0.01165
[79]	train-mlogloss:0.02159	eval-mlogloss:0.01141
[80]	train-mlogloss:0.02147	eval-mlogloss:0.01153
[81]	train-mlogloss:0.02142	eval-mlogloss:0.01166
[82]	train-mlogloss:0.02134	eval-mlogloss:0.01184
[83]	train-mlogloss:0.02121	eval-mlogloss:0.01205
[84]	train-mlogloss:0.02121	eval-mlogloss:0.01225
[85]	train-mlogloss:0.02113	eval-mlogloss:0.01206
[86]	train-mlogloss:0.02111	eval-mlogloss:0.01196
[87]	train-mlogloss:0.02105	eval-mlogloss:0.01213
[88]	train-mlogloss:0.02097	eval-mlogloss:0.01218
[89]	train-mlogloss:0.02084	eval-mlogloss:0.01200
[90]	train-mlogloss:0.02082	eval-mlogloss:0.01212
[91]	train-mlogloss:0.02079	eval-mlogloss:0.01225
[92]	train-mlogloss:0.02070	eval-mlogloss:0.01266
[93]	train-mlogloss:0.02069	eval-mlogloss:0.01228
[94]	train-mlogloss:0.02067	eval-mlogloss:0.01197
[95]	train-mlogloss:0.02062	eval-mlogloss:0.01208
[96]	train-mlogloss:0.02060	eval-mlogloss:0.01213
[97]	train-mlogloss:0.02055	eval-mlogloss:0.01199
[98]	train-mlogloss:0.02050	eval-mlogloss:0.01208
[99]	train-mlogloss:0.02044	eval-mlogloss:0.01180

[I 2026-09-28 23:31:17,826] Trial 0 finished with value: 1.0 and parameters: {'lambda': 4.1337559910672894e-05, 'alpha': 0.011808853729328387, 'eta': 0.24005561243597381, 'gamma': 0.011928557488665113, 'max_depth': 9, 'min_child_weight': 1, 'subsample': 0.7798325311658101, 'colsample_bytree': 0.7619585418840047}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.05116	eval-mlogloss:1.05203
[1]	train-mlogloss:1.00427	eval-mlogloss:1.00422
[2]	train-mlogloss:0.95916	eval-mlogloss:0.95631
[3]	train-mlogloss:0.91759	eval-mlogloss:0.91221
[4]	train-mlogloss:0.87901	eval-mlogloss:0.87236
[5]	train-mlogloss:0.84210	eval-mlogloss:0.83129
[6]	train-mlogloss:0.81131	eval-mlogloss:0.79936
[7]	train-mlogloss:0.77847	eval-mlogloss:0.76427
[8]	train-mlogloss:0.74736	eval-mlogloss:0.73085
[9]	train-mlogloss:0.71845	eval-mlogloss:0.69991
[10]	train-mlogloss:0.69352	eval-mlogloss:0.67340
[11]	train-mlogloss:0.66739	eval-mlogloss:0.64529
[12]	train-mlogloss:0.64197	eval-mlogloss:0.61848
[13]	train-mlogloss:0.61752	eval-mlogloss:0.59301
[14]	train-mlogloss:0.59469	eval-mlogloss:0.56889
[15]	train-mlogloss:0.57505	eval-mlogloss:0.54822
[16]	train-mlogloss:0.55507	eval-mlogloss:0.52635
[17]	train-mlogloss:0.53578	eval-mlogloss:0.50617
[18]	train-mlogloss:0.52022	eval-mlogloss:0.49092
[19]	train-mlogloss:0.50767	eval-mlogloss:0.47704
[20]	train-mlogloss:0.49135	eval-mlogloss:0.45880
[21]	train-mlogloss:0.47642	eval-mlogloss:0.44285
[22]	train-mlogloss:0.46550	eval-mlogloss:0.42962
[23]	train-mlogloss:0.45222	eval-mlogloss:0.41511
[24]	train-mlogloss:0.44016	eval-mlogloss:0.40176
[25]	train-mlogloss:0.42759	eval-mlogloss:0.38723
[26]	train-mlogloss:0.41491	eval-mlogloss:0.37243
[27]	train-mlogloss:0.40246	eval-mlogloss:0.35932
[28]	train-mlogloss:0.39255	eval-mlogloss:0.34798
[29]	train-mlogloss:0.38431	eval-mlogloss:0.33894
[30]	train-mlogloss:0.37684	eval-mlogloss:0.33064
[31]	train-mlogloss:0.36861	eval-mlogloss:0.32222
[32]	train-mlogloss:0.36110	eval-mlogloss:0.31433
[33]	train-mlogloss:0.35203	eval-mlogloss:0.30382
[34]	train-mlogloss:0.34482	eval-mlogloss:0.29605
[35]	train-mlogloss:0.33862	eval-mlogloss:0.28873
[36]	train-mlogloss:0.33334	eval-mlogloss:0.28356
[37]	train-mlogloss:0.32691	eval-mlogloss:0.27674
[38]	train-mlogloss:0.31900	eval-mlogloss:0.26803
[39]	train-mlogloss:0.31371	eval-mlogloss:0.26195
[40]	train-mlogloss:0.30831	eval-mlogloss:0.25584
[41]	train-mlogloss:0.30326	eval-mlogloss:0.25038
[42]	train-mlogloss:0.29868	eval-mlogloss:0.24580
[43]	train-mlogloss:0.29626	eval-mlogloss:0.24241
[44]	train-mlogloss:0.29136	eval-mlogloss:0.23680
[45]	train-mlogloss:0.28647	eval-mlogloss:0.23113
[46]	train-mlogloss:0.28368	eval-mlogloss:0.22735
[47]	train-mlogloss:0.28214	eval-mlogloss:0.22520
[48]	train-mlogloss:0.28189	eval-mlogloss:0.22489
[49]	train-mlogloss:0.27988	eval-mlogloss:0.22260
[50]	train-mlogloss:0.27565	eval-mlogloss:0.21799
[51]	train-mlogloss:0.27316	eval-mlogloss:0.21567
[52]	train-mlogloss:0.27126	eval-mlogloss:0.21321
[53]	train-mlogloss:0.26707	eval-mlogloss:0.20883
[54]	train-mlogloss:0.26342	eval-mlogloss:0.20506
[55]	train-mlogloss:0.26116	eval-mlogloss:0.20165
[56]	train-mlogloss:0.26116	eval-mlogloss:0.20164
[57]	train-mlogloss:0.25983	eval-mlogloss:0.20007
[58]	train-mlogloss:0.25854	eval-mlogloss:0.19852
[59]	train-mlogloss:0.25750	eval-mlogloss:0.19737
[60]	train-mlogloss:0.25630	eval-mlogloss:0.19587
[61]	train-mlogloss:0.25610	eval-mlogloss:0.19583
[62]	train-mlogloss:0.25599	eval-mlogloss:0.19574
[63]	train-mlogloss:0.25577	eval-mlogloss:0.19548
[64]	train-mlogloss:0.25568	eval-mlogloss:0.19543
[65]	train-mlogloss:0.25255	eval-mlogloss:0.19189
[66]	train-mlogloss:0.25252	eval-mlogloss:0.19190
[67]	train-mlogloss:0.25252	eval-mlogloss:0.19190
[68]	train-mlogloss:0.25241	eval-mlogloss:0.19191
[69]	train-mlogloss:0.25222	eval-mlogloss:0.19177
[70]	train-mlogloss:0.25201	eval-mlogloss:0.19162
[71]	train-mlogloss:0.25194	eval-mlogloss:0.19165
[72]	train-mlogloss:0.25184	eval-mlogloss:0.19135
[73]	train-mlogloss:0.25177	eval-mlogloss:0.19120
[74]	train-mlogloss:0.24966	eval-mlogloss:0.18924
[75]	train-mlogloss:0.24956	eval-mlogloss:0.18889
[76]	train-mlogloss:0.24795	eval-mlogloss:0.18680
[77]	train-mlogloss:0.24771	eval-mlogloss:0.18656
[78]	train-mlogloss:0.24770	eval-mlogloss:0.18653
[79]	train-mlogloss:0.24660	eval-mlogloss:0.18516
[80]	train-mlogloss:0.24657	eval-mlogloss:0.18515
[81]	train-mlogloss:0.24657	eval-mlogloss:0.18515
[82]	train-mlogloss:0.24641	eval-mlogloss:0.18465
[83]	train-mlogloss:0.24634	eval-mlogloss:0.18449
[84]	train-mlogloss:0.24634	eval-mlogloss:0.18448
[85]	train-mlogloss:0.24632	eval-mlogloss:0.18446
[86]	train-mlogloss:0.24629	eval-mlogloss:0.18443
[87]	train-mlogloss:0.24628	eval-mlogloss:0.18440
[88]	train-mlogloss:0.24555	eval-mlogloss:0.18330
[89]	train-mlogloss:0.24546	eval-mlogloss:0.18303
[90]	train-mlogloss:0.24543	eval-mlogloss:0.18298
[91]	train-mlogloss:0.24543	eval-mlogloss:0.18294
[92]	train-mlogloss:0.24536	eval-mlogloss:0.18275
[93]	train-mlogloss:0.24531	eval-mlogloss:0.18263
[94]	train-mlogloss:0.24522	eval-mlogloss:0.18260
[95]	train-mlogloss:0.24516	eval-mlogloss:0.18241
[96]	train-mlogloss:0.24516	eval-mlogloss:0.18240
[97]	train-mlogloss:0.24499	eval-mlogloss:0.18228
[98]	train-mlogloss:0.24487	eval-mlogloss:0.18224
[99]	train-mlogloss:0.24481	eval-mlogloss:0.18228
[100]	train-mlogloss:0.24388	eval-mlogloss:0.18118
[101]	train-mlogloss:0.24225	eval-mlogloss:0.17952
[102]	train-mlogloss:0.24212	eval-mlogloss:0.17951
[103]	train-mlogloss:0.24208	eval-mlogloss:0.17950
[104]	train-mlogloss:0.24202	eval-mlogloss:0.17946
[105]	train-mlogloss:0.24193	eval-mlogloss:0.17913
[106]	train-mlogloss:0.24182	eval-mlogloss:0.17908
[107]	train-mlogloss:0.24081	eval-mlogloss:0.17786
[108]	train-mlogloss:0.24077	eval-mlogloss:0.17785
[109]	train-mlogloss:0.24074	eval-mlogloss:0.17777
[110]	train-mlogloss:0.24072	eval-mlogloss:0.17773
[111]	train-mlogloss:0.24064	eval-mlogloss:0.17773
[112]	train-mlogloss:0.24045	eval-mlogloss:0.17751
[113]	train-mlogloss:0.24045	eval-mlogloss:0.17747
[114]	train-mlogloss:0.23906	eval-mlogloss:0.17566
[115]	train-mlogloss:0.23900	eval-mlogloss:0.17562
[116]	train-mlogloss:0.23897	eval-mlogloss:0.17561
[117]	train-mlogloss:0.23803	eval-mlogloss:0.17445
[118]	train-mlogloss:0.23789	eval-mlogloss:0.17458
[119]	train-mlogloss:0.23773	eval-mlogloss:0.17461
[120]	train-mlogloss:0.23762	eval-mlogloss:0.17451
[121]	train-mlogloss:0.23763	eval-mlogloss:0.17457
[122]	train-mlogloss:0.23663	eval-mlogloss:0.17322
[123]	train-mlogloss:0.23663	eval-mlogloss:0.17319
[124]	train-mlogloss:0.23661	eval-mlogloss:0.17315
[125]	train-mlogloss:0.23655	eval-mlogloss:0.17306
[126]	train-mlogloss:0.23648	eval-mlogloss:0.17295
[127]	train-mlogloss:0.23643	eval-mlogloss:0.17295
[128]	train-mlogloss:0.23634	eval-mlogloss:0.17284
[129]	train-mlogloss:0.23633	eval-mlogloss:0.17282
[130]	train-mlogloss:0.23558	eval-mlogloss:0.17171
[131]	train-mlogloss:0.23476	eval-mlogloss:0.17039
[132]	train-mlogloss:0.23453	eval-mlogloss:0.17001
[133]	train-mlogloss:0.23441	eval-mlogloss:0.16959
[134]	train-mlogloss:0.23414	eval-mlogloss:0.16918
[135]	train-mlogloss:0.23411	eval-mlogloss:0.16902
[136]	train-mlogloss:0.23408	eval-mlogloss:0.16900
[137]	train-mlogloss:0.23409	eval-mlogloss:0.16901
[138]	train-mlogloss:0.23409	eval-mlogloss:0.16899
[139]	train-mlogloss:0.23404	eval-mlogloss:0.16896
[140]	train-mlogloss:0.23404	eval-mlogloss:0.16892
[141]	train-mlogloss:0.23400	eval-mlogloss:0.16878
[142]	train-mlogloss:0.23399	eval-mlogloss:0.16880
[143]	train-mlogloss:0.23389	eval-mlogloss:0.16864
[144]	train-mlogloss:0.23303	eval-mlogloss:0.16762
[145]	train-mlogloss:0.23290	eval-mlogloss:0.16761
[146]	train-mlogloss:0.23289	eval-mlogloss:0.16760
[147]	train-mlogloss:0.23183	eval-mlogloss:0.16634
[148]	train-mlogloss:0.23184	eval-mlogloss:0.16639
[149]	train-mlogloss:0.23167	eval-mlogloss:0.16617
[150]	train-mlogloss:0.23164	eval-mlogloss:0.16617
[151]	train-mlogloss:0.23164	eval-mlogloss:0.16617
[152]	train-mlogloss:0.23154	eval-mlogloss:0.16609
[153]	train-mlogloss:0.23147	eval-mlogloss:0.16579
[154]	train-mlogloss:0.23137	eval-mlogloss:0.16573
[155]	train-mlogloss:0.23137	eval-mlogloss:0.16573
[156]	train-mlogloss:0.23032	eval-mlogloss:0.16433
[157]	train-mlogloss:0.23033	eval-mlogloss:0.16439
[158]	train-mlogloss:0.23033	eval-mlogloss:0.16442
[159]	train-mlogloss:0.23032	eval-mlogloss:0.16437
[160]	train-mlogloss:0.23020	eval-mlogloss:0.16431
[161]	train-mlogloss:0.23011	eval-mlogloss:0.16396
[162]	train-mlogloss:0.23008	eval-mlogloss:0.16385
[163]	train-mlogloss:0.23005	eval-mlogloss:0.16383
[164]	train-mlogloss:0.23005	eval-mlogloss:0.16385
[165]	train-mlogloss:0.23005	eval-mlogloss:0.16385
[166]	train-mlogloss:0.23004	eval-mlogloss:0.16385
[167]	train-mlogloss:0.23005	eval-mlogloss:0.16389
[168]	train-mlogloss:0.23005	eval-mlogloss:0.16392
[169]	train-mlogloss:0.23003	eval-mlogloss:0.16389
[170]	train-mlogloss:0.23001	eval-mlogloss:0.16389
[171]	train-mlogloss:0.22990	eval-mlogloss:0.16376
[172]	train-mlogloss:0.22987	eval-mlogloss:0.16362
[173]	train-mlogloss:0.22985	eval-mlogloss:0.16360
[174]	train-mlogloss:0.22977	eval-mlogloss:0.16357
[175]	train-mlogloss:0.22970	eval-mlogloss:0.16331
[176]	train-mlogloss:0.22963	eval-mlogloss:0.16331
[177]	train-mlogloss:0.22959	eval-mlogloss:0.16313
[178]	train-mlogloss:0.22957	eval-mlogloss:0.16307
[179]	train-mlogloss:0.22951	eval-mlogloss:0.16305
[180]	train-mlogloss:0.22950	eval-mlogloss:0.16299
[181]	train-mlogloss:0.22949	eval-mlogloss:0.16294
[182]	train-mlogloss:0.22944	eval-mlogloss:0.16286
[183]	train-mlogloss:0.22944	eval-mlogloss:0.16286
[184]	train-mlogloss:0.22943	eval-mlogloss:0.16282
[185]	train-mlogloss:0.22944	eval-mlogloss:0.16278
[186]	train-mlogloss:0.22944	eval-mlogloss:0.16281
[187]	train-mlogloss:0.22939	eval-mlogloss:0.16282
[188]	train-mlogloss:0.22933	eval-mlogloss:0.16288
[189]	train-mlogloss:0.22927	eval-mlogloss:0.16264
[190]	train-mlogloss:0.22927	eval-mlogloss:0.16261
[191]	train-mlogloss:0.22926	eval-mlogloss:0.16261
[192]	train-mlogloss:0.22925	eval-mlogloss:0.16252
[193]	train-mlogloss:0.22923	eval-mlogloss:0.16250
[194]	train-mlogloss:0.22918	eval-mlogloss:0.16245
[195]	train-mlogloss:0.22916	eval-mlogloss:0.16238
[196]	train-mlogloss:0.22916	eval-mlogloss:0.16238
[197]	train-mlogloss:0.22914	eval-mlogloss:0.16243
[198]	train-mlogloss:0.22912	eval-mlogloss:0.16244
[199]	train-mlogloss:0.22904	eval-mlogloss:0.16243
[200]	train-mlogloss:0.22904	eval-mlogloss:0.16243
[201]	train-mlogloss:0.22904	eval-mlogloss:0.16244
[202]	train-mlogloss:0.22900	eval-mlogloss:0.16227
[203]	train-mlogloss:0.22901	eval-mlogloss:0.16229
[204]	train-mlogloss:0.22886	eval-mlogloss:0.16222
[205]	train-mlogloss:0.22881	eval-mlogloss:0.16221
[206]	train-mlogloss:0.22880	eval-mlogloss:0.16224
[207]	train-mlogloss:0.22878	eval-mlogloss:0.16221
[208]	train-mlogloss:0.22876	eval-mlogloss:0.16222
[209]	train-mlogloss:0.22877	eval-mlogloss:0.16223
[210]	train-mlogloss:0.22875	eval-mlogloss:0.16227
[211]	train-mlogloss:0.22862	eval-mlogloss:0.16208
[212]	train-mlogloss:0.22859	eval-mlogloss:0.16207
[213]	train-mlogloss:0.22855	eval-mlogloss:0.16194
[214]	train-mlogloss:0.22856	eval-mlogloss:0.16195
[215]	train-mlogloss:0.22855	eval-mlogloss:0.16192
[216]	train-mlogloss:0.22855	eval-mlogloss:0.16196
[217]	train-mlogloss:0.22854	eval-mlogloss:0.16192
[218]	train-mlogloss:0.22853	eval-mlogloss:0.16190
[219]	train-mlogloss:0.22852	eval-mlogloss:0.16185
[220]	train-mlogloss:0.22852	eval-mlogloss:0.16184
[221]	train-mlogloss:0.22849	eval-mlogloss:0.16183
[222]	train-mlogloss:0.22849	eval-mlogloss:0.16182
[223]	train-mlogloss:0.22811	eval-mlogloss:0.16144
[224]	train-mlogloss:0.22805	eval-mlogloss:0.16146
[225]	train-mlogloss:0.22804	eval-mlogloss:0.16142
[226]	train-mlogloss:0.22806	eval-mlogloss:0.16146
[227]	train-mlogloss:0.22803	eval-mlogloss:0.16143
[228]	train-mlogloss:0.22800	eval-mlogloss:0.16133
[229]	train-mlogloss:0.22801	eval-mlogloss:0.16137
[230]	train-mlogloss:0.22801	eval-mlogloss:0.16132
[231]	train-mlogloss:0.22797	eval-mlogloss:0.16131
[232]	train-mlogloss:0.22790	eval-mlogloss:0.16135
[233]	train-mlogloss:0.22783	eval-mlogloss:0.16113
[234]	train-mlogloss:0.22783	eval-mlogloss:0.16115
[235]	train-mlogloss:0.22771	eval-mlogloss:0.16113
[236]	train-mlogloss:0.22761	eval-mlogloss:0.16102
[237]	train-mlogloss:0.22761	eval-mlogloss:0.16102
[238]	train-mlogloss:0.22753	eval-mlogloss:0.16067
[239]	train-mlogloss:0.22753	eval-mlogloss:0.16065
[240]	train-mlogloss:0.22753	eval-mlogloss:0.16062
[241]	train-mlogloss:0.22753	eval-mlogloss:0.16060
[242]	train-mlogloss:0.22752	eval-mlogloss:0.16060
[243]	train-mlogloss:0.22751	eval-mlogloss:0.16056
[244]	train-mlogloss:0.22751	eval-mlogloss:0.16056
[245]	train-mlogloss:0.22745	eval-mlogloss:0.16030
[246]	train-mlogloss:0.22746	eval-mlogloss:0.16035
[247]	train-mlogloss:0.22745	eval-mlogloss:0.16034
[248]	train-mlogloss:0.22738	eval-mlogloss:0.16003
[249]	train-mlogloss:0.22738	eval-mlogloss:0.16001
[250]	train-mlogloss:0.22739	eval-mlogloss:0.16002
[251]	train-mlogloss:0.22738	eval-mlogloss:0.16001
[252]	train-mlogloss:0.22732	eval-mlogloss:0.15999
[253]	train-mlogloss:0.22727	eval-mlogloss:0.15985
[254]	train-mlogloss:0.22730	eval-mlogloss:0.15992
[255]	train-mlogloss:0.22723	eval-mlogloss:0.15973
[256]	train-mlogloss:0.22716	eval-mlogloss:0.15969
[257]	train-mlogloss:0.22714	eval-mlogloss:0.15968
[258]	train-mlogloss:0.22714	eval-mlogloss:0.15967
[259]	train-mlogloss:0.22711	eval-mlogloss:0.15966
[260]	train-mlogloss:0.22709	eval-mlogloss:0.15963
[261]	train-mlogloss:0.22709	eval-mlogloss:0.15962
[262]	train-mlogloss:0.22709	eval-mlogloss:0.15963
[263]	train-mlogloss:0.22705	eval-mlogloss:0.15967
[264]	train-mlogloss:0.22690	eval-mlogloss:0.15973
[265]	train-mlogloss:0.22689	eval-mlogloss:0.15975
[266]	train-mlogloss:0.22690	eval-mlogloss:0.15975
[267]	train-mlogloss:0.22689	eval-mlogloss:0.15974
[268]	train-mlogloss:0.22690	eval-mlogloss:0.15973
[269]	train-mlogloss:0.22691	eval-mlogloss:0.15976
[270]	train-mlogloss:0.22686	eval-mlogloss:0.15962
[271]	train-mlogloss:0.22685	eval-mlogloss:0.15964
[272]	train-mlogloss:0.22685	eval-mlogloss:0.15963
[273]	train-mlogloss:0.22677	eval-mlogloss:0.15953
[274]	train-mlogloss:0.22676	eval-mlogloss:0.15952
[275]	train-mlogloss:0.22676	eval-mlogloss:0.15952
[276]	train-mlogloss:0.22676	eval-mlogloss:0.15952
[277]	train-mlogloss:0.22676	eval-mlogloss:0.15949
[278]	train-mlogloss:0.22676	eval-mlogloss:0.15947
[279]	train-mlogloss:0.22676	eval-mlogloss:0.15946
[280]	train-mlogloss:0.22676	eval-mlogloss:0.15947
[281]	train-mlogloss:0.22676	eval-mlogloss:0.15947
[282]	train-mlogloss:0.22677	eval-mlogloss:0.15941
[283]	train-mlogloss:0.22672	eval-mlogloss:0.15926
[284]	train-mlogloss:0.22671	eval-mlogloss:0.15924
[285]	train-mlogloss:0.22664	eval-mlogloss:0.15925
[286]	train-mlogloss:0.22664	eval-mlogloss:0.15925
[287]	train-mlogloss:0.22656	eval-mlogloss:0.15927
[288]	train-mlogloss:0.22656	eval-mlogloss:0.15927
[289]	train-mlogloss:0.22656	eval-mlogloss:0.15922
[290]	train-mlogloss:0.22656	eval-mlogloss:0.15920
[291]	train-mlogloss:0.22653	eval-mlogloss:0.15902
[292]	train-mlogloss:0.22634	eval-mlogloss:0.15867
[293]	train-mlogloss:0.22634	eval-mlogloss:0.15866
[294]	train-mlogloss:0.22634	eval-mlogloss:0.15865
[295]	train-mlogloss:0.22634	eval-mlogloss:0.15864
[296]	train-mlogloss:0.22626	eval-mlogloss:0.15865
[297]	train-mlogloss:0.22620	eval-mlogloss:0.15867
[298]	train-mlogloss:0.22620	eval-mlogloss:0.15867
[299]	train-mlogloss:0.22610	eval-mlogloss:0.15868

[I 2026-09-28 23:31:23,454] Trial 1 finished with value: 1.0 and parameters: {'lambda': 0.00043454356035212333, 'alpha': 0.5883278049083334, 'eta': 0.04160337103547449, 'gamma': 2.7390682544338783e-07, 'max_depth': 8, 'min_child_weight': 7, 'subsample': 0.5601290574228397, 'colsample_bytree': 0.9595150633320536}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.01810	eval-mlogloss:1.01564

[I 2026-09-28 23:31:23,503] Trial 2 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.87941	eval-mlogloss:0.86795

[I 2026-09-28 23:31:23,555] Trial 3 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.06915	eval-mlogloss:1.07138
[1]	train-mlogloss:1.03644	eval-mlogloss:1.03751
[2]	train-mlogloss:1.02855	eval-mlogloss:1.03054
[3]	train-mlogloss:1.01489	eval-mlogloss:1.01548
[4]	train-mlogloss:0.99116	eval-mlogloss:0.99177
[5]	train-mlogloss:0.97624	eval-mlogloss:0.97776
[6]	train-mlogloss:0.95272	eval-mlogloss:0.95355
[7]	train-mlogloss:0.93690	eval-mlogloss:0.93704
[8]	train-mlogloss:0.91990	eval-mlogloss:0.92254
[9]	train-mlogloss:0.89739	eval-mlogloss:0.89758
[10]	train-mlogloss:0.89213	eval-mlogloss:0.89266
[11]	train-mlogloss:0.87222	eval-mlogloss:0.87194
[12]	train-mlogloss:0.86138	eval-mlogloss:0.86010
[13]	train-mlogloss:0.84757	eval-mlogloss:0.84624
[14]	train-mlogloss:0.83675	eval-mlogloss:0.83426
[15]	train-mlogloss:0.82392	eval-mlogloss:0.82142
[16]	train-mlogloss:0.80982	eval-mlogloss:0.80658
[17]	train-mlogloss:0.80334	eval-mlogloss:0.80041
[18]	train-mlogloss:0.79139	eval-mlogloss:0.78767
[19]	train-mlogloss:0.77621	eval-mlogloss:0.77123
[20]	train-mlogloss:0.76013	eval-mlogloss:0.75293
[21]	train-mlogloss:0.74876	eval-mlogloss:0.74197
[22]	train-mlogloss:0.73514	eval-mlogloss:0.72731
[23]	train-mlogloss:0.71671	eval-mlogloss:0.70700
[24]	train-mlogloss:0.70021	eval-mlogloss:0.68873
[25]	train-mlogloss:0.68675	eval-mlogloss:0.67442
[26]	train-mlogloss:0.66833	eval-mlogloss:0.65443
[27]	train-mlogloss:0.65009	eval-mlogloss:0.63476
[28]	train-mlogloss:0.64023	eval-mlogloss:0.62357
[29]	train-mlogloss:0.62798	eval-mlogloss:0.61041
[30]	train-mlogloss:0.61968	eval-mlogloss:0.60118
[31]	train-mlogloss:0.61078	eval-mlogloss:0.59099
[32]	train-mlogloss:0.60199	eval-mlogloss:0.58170
[33]	train-mlogloss:0.59449	eval-mlogloss:0.57409
[34]	train-mlogloss:0.58928	eval-mlogloss:0.56770
[35]	train-mlogloss:0.57877	eval-mlogloss:0.55547
[36]	train-mlogloss:0.57239	eval-mlogloss:0.54934
[37]	train-mlogloss:0.56656	eval-mlogloss:0.54342
[38]	train-mlogloss:0.55833	eval-mlogloss:0.53489
[39]	train-mlogloss:0.55081	eval-mlogloss:0.52637
[40]	train-mlogloss:0.54205	eval-mlogloss:0.51648
[41]	train-mlogloss:0.53193	eval-mlogloss:0.50514
[42]	train-mlogloss:0.52256	eval-mlogloss:0.49423
[43]	train-mlogloss:0.51931	eval-mlogloss:0.49164
[44]	train-mlogloss:0.51325	eval-mlogloss:0.48592
[45]	train-mlogloss:0.50685	eval-mlogloss:0.47900
[46]	train-mlogloss:0.49834	eval-mlogloss:0.46923
[47]	train-mlogloss:0.49222	eval-mlogloss:0.46246
[48]	train-mlogloss:0.48551	eval-mlogloss:0.45535
[49]	train-mlogloss:0.47462	eval-mlogloss:0.44224
[50]	train-mlogloss:0.46854	eval-mlogloss:0.43560
[51]	train-mlogloss:0.46510	eval-mlogloss:0.43171
[52]	train-mlogloss:0.45575	eval-mlogloss:0.42058
[53]	train-mlogloss:0.45026	eval-mlogloss:0.41507
[54]	train-mlogloss:0.44653	eval-mlogloss:0.41106
[55]	train-mlogloss:0.44027	eval-mlogloss:0.40337
[56]	train-mlogloss:0.43587	eval-mlogloss:0.39873
[57]	train-mlogloss:0.43305	eval-mlogloss:0.39549
[58]	train-mlogloss:0.42811	eval-mlogloss:0.38956
[59]	train-mlogloss:0.42247	eval-mlogloss:0.38390
[60]	train-mlogloss:0.41483	eval-mlogloss:0.37556
[61]	train-mlogloss:0.41124	eval-mlogloss:0.37194
[62]	train-mlogloss:0.40865	eval-mlogloss:0.36954
[63]	train-mlogloss:0.40309	eval-mlogloss:0.36339
[64]	train-mlogloss:0.40221	eval-mlogloss:0.36226
[65]	train-mlogloss:0.39909	eval-mlogloss:0.35882
[66]	train-mlogloss:0.39531	eval-mlogloss:0.35400
[67]	train-mlogloss:0.39337	eval-mlogloss:0.35178
[68]	train-mlogloss:0.39070	eval-mlogloss:0.34930
[69]	train-mlogloss:0.38836	eval-mlogloss:0.34650
[70]	train-mlogloss:0.38586	eval-mlogloss:0.34392
[71]	train-mlogloss:0.38313	eval-mlogloss:0.34069
[72]	train-mlogloss:0.37701	eval-mlogloss:0.33395
[73]	train-mlogloss:0.37625	eval-mlogloss:0.33266
[74]	train-mlogloss:0.37218	eval-mlogloss:0.32810
[75]	train-mlogloss:0.37187	eval-mlogloss:0.32753
[76]	train-mlogloss:0.37140	eval-mlogloss:0.32674
[77]	train-mlogloss:0.37061	eval-mlogloss:0.32544
[78]	train-mlogloss:0.37032	eval-mlogloss:0.32491
[79]	train-mlogloss:0.36798	eval-mlogloss:0.32256
[80]	train-mlogloss:0.36794	eval-mlogloss:0.32257
[81]	train-mlogloss:0.36785	eval-mlogloss:0.32256
[82]	train-mlogloss:0.36764	eval-mlogloss:0.32265
[83]	train-mlogloss:0.36392	eval-mlogloss:0.31829
[84]	train-mlogloss:0.36390	eval-mlogloss:0.31831
[85]	train-mlogloss:0.36262	eval-mlogloss:0.31771
[86]	train-mlogloss:0.35995	eval-mlogloss:0.31448
[87]	train-mlogloss:0.35970	eval-mlogloss:0.31430
[88]	train-mlogloss:0.35911	eval-mlogloss:0.31400
[89]	train-mlogloss:0.35856	eval-mlogloss:0.31380
[90]	train-mlogloss:0.35834	eval-mlogloss:0.31355
[91]	train-mlogloss:0.35774	eval-mlogloss:0.31258
[92]	train-mlogloss:0.35676	eval-mlogloss:0.31066
[93]	train-mlogloss:0.35538	eval-mlogloss:0.30901
[94]	train-mlogloss:0.35305	eval-mlogloss:0.30645
[95]	train-mlogloss:0.35291	eval-mlogloss:0.30635
[96]	train-mlogloss:0.35076	eval-mlogloss:0.30392
[97]	train-mlogloss:0.34825	eval-mlogloss:0.30165
[98]	train-mlogloss:0.34770	eval-mlogloss:0.30090
[99]	train-mlogloss:0.34764	eval-mlogloss:0.30083
[100]	train-mlogloss:0.34477	eval-mlogloss:0.29802
[101]	train-mlogloss:0.34208	eval-mlogloss:0.29509
[102]	train-mlogloss:0.34208	eval-mlogloss:0.29510
[103]	train-mlogloss:0.34205	eval-mlogloss:0.29516
[104]	train-mlogloss:0.34015	eval-mlogloss:0.29307
[105]	train-mlogloss:0.33586	eval-mlogloss:0.28832
[106]	train-mlogloss:0.33377	eval-mlogloss:0.28601
[107]	train-mlogloss:0.33188	eval-mlogloss:0.28370
[108]	train-mlogloss:0.33171	eval-mlogloss:0.28353
[109]	train-mlogloss:0.33109	eval-mlogloss:0.28284
[110]	train-mlogloss:0.33090	eval-mlogloss:0.28234
[111]	train-mlogloss:0.33072	eval-mlogloss:0.28198
[112]	train-mlogloss:0.33047	eval-mlogloss:0.28183
[113]	train-mlogloss:0.32880	eval-mlogloss:0.27951
[114]	train-mlogloss:0.32851	eval-mlogloss:0.27919
[115]	train-mlogloss:0.32682	eval-mlogloss:0.27744
[116]	train-mlogloss:0.32531	eval-mlogloss:0.27541
[117]	train-mlogloss:0.32344	eval-mlogloss:0.27287
[118]	train-mlogloss:0.32210	eval-mlogloss:0.27109
[119]	train-mlogloss:0.32008	eval-mlogloss:0.26897
[120]	train-mlogloss:0.31985	eval-mlogloss:0.26866
[121]	train-mlogloss:0.31987	eval-mlogloss:0.26883
[122]	train-mlogloss:0.31973	eval-mlogloss:0.26886
[123]	train-mlogloss:0.31952	eval-mlogloss:0.26865
[124]	train-mlogloss:0.31750	eval-mlogloss:0.26668
[125]	train-mlogloss:0.31748	eval-mlogloss:0.26663
[126]	train-mlogloss:0.31753	eval-mlogloss:0.26674
[127]	train-mlogloss:0.31716	eval-mlogloss:0.26623
[128]	train-mlogloss:0.31706	eval-mlogloss:0.26610
[129]	train-mlogloss:0.31706	eval-mlogloss:0.26608
[130]	train-mlogloss:0.31521	eval-mlogloss:0.26401
[131]	train-mlogloss:0.31494	eval-mlogloss:0.26362
[132]	train-mlogloss:0.31484	eval-mlogloss:0.26348
[133]	train-mlogloss:0.31449	eval-mlogloss:0.26336
[134]	train-mlogloss:0.31450	eval-mlogloss:0.26332
[135]	train-mlogloss:0.31441	eval-mlogloss:0.26290
[136]	train-mlogloss:0.31277	eval-mlogloss:0.26075
[137]	train-mlogloss:0.30962	eval-mlogloss:0.25708
[138]	train-mlogloss:0.30812	eval-mlogloss:0.25528
[139]	train-mlogloss:0.30801	eval-mlogloss:0.25525
[140]	train-mlogloss:0.30654	eval-mlogloss:0.25301
[141]	train-mlogloss:0.30645	eval-mlogloss:0.25287
[142]	train-mlogloss:0.30644	eval-mlogloss:0.25292
[143]	train-mlogloss:0.30637	eval-mlogloss:0.25285
[144]	train-mlogloss:0.30617	eval-mlogloss:0.25242
[145]	train-mlogloss:0.30591	eval-mlogloss:0.25238
[146]	train-mlogloss:0.30466	eval-mlogloss:0.25076
[147]	train-mlogloss:0.30465	eval-mlogloss:0.25078
[148]	train-mlogloss:0.30446	eval-mlogloss:0.25050
[149]	train-mlogloss:0.30431	eval-mlogloss:0.25039
[150]	train-mlogloss:0.30431	eval-mlogloss:0.25042
[151]	train-mlogloss:0.30431	eval-mlogloss:0.25041
[152]	train-mlogloss:0.30283	eval-mlogloss:0.24878
[153]	train-mlogloss:0.30272	eval-mlogloss:0.24836
[154]	train-mlogloss:0.30260	eval-mlogloss:0.24838
[155]	train-mlogloss:0.30122	eval-mlogloss:0.24680
[156]	train-mlogloss:0.30083	eval-mlogloss:0.24624
[157]	train-mlogloss:0.30083	eval-mlogloss:0.24630
[158]	train-mlogloss:0.30067	eval-mlogloss:0.24659
[159]	train-mlogloss:0.30066	eval-mlogloss:0.24657
[160]	train-mlogloss:0.30066	eval-mlogloss:0.24654
[161]	train-mlogloss:0.30042	eval-mlogloss:0.24564
[162]	train-mlogloss:0.30032	eval-mlogloss:0.24523
[163]	train-mlogloss:0.30032	eval-mlogloss:0.24522
[164]	train-mlogloss:0.29881	eval-mlogloss:0.24383
[165]	train-mlogloss:0.29881	eval-mlogloss:0.24380
[166]	train-mlogloss:0.29875	eval-mlogloss:0.24373
[167]	train-mlogloss:0.29847	eval-mlogloss:0.24333
[168]	train-mlogloss:0.29851	eval-mlogloss:0.24334
[169]	train-mlogloss:0.29844	eval-mlogloss:0.24317
[170]	train-mlogloss:0.29835	eval-mlogloss:0.24294
[171]	train-mlogloss:0.29835	eval-mlogloss:0.24293
[172]	train-mlogloss:0.29687	eval-mlogloss:0.24122
[173]	train-mlogloss:0.29672	eval-mlogloss:0.24098
[174]	train-mlogloss:0.29670	eval-mlogloss:0.24107
[175]	train-mlogloss:0.29659	eval-mlogloss:0.24068
[176]	train-mlogloss:0.29643	eval-mlogloss:0.24044
[177]	train-mlogloss:0.29632	eval-mlogloss:0.24035
[178]	train-mlogloss:0.29587	eval-mlogloss:0.23993
[179]	train-mlogloss:0.29564	eval-mlogloss:0.23957
[180]	train-mlogloss:0.29563	eval-mlogloss:0.23955
[181]	train-mlogloss:0.29564	eval-mlogloss:0.23947
[182]	train-mlogloss:0.29570	eval-mlogloss:0.23938
[183]	train-mlogloss:0.29570	eval-mlogloss:0.23941
[184]	train-mlogloss:0.29562	eval-mlogloss:0.23917
[185]	train-mlogloss:0.29563	eval-mlogloss:0.23907
[186]	train-mlogloss:0.29565	eval-mlogloss:0.23898
[187]	train-mlogloss:0.29565	eval-mlogloss:0.23900
[188]	train-mlogloss:0.29553	eval-mlogloss:0.23917
[189]	train-mlogloss:0.29537	eval-mlogloss:0.23851
[190]	train-mlogloss:0.29528	eval-mlogloss:0.23837
[191]	train-mlogloss:0.29528	eval-mlogloss:0.23837
[192]	train-mlogloss:0.29508	eval-mlogloss:0.23787
[193]	train-mlogloss:0.29506	eval-mlogloss:0.23790
[194]	train-mlogloss:0.29499	eval-mlogloss:0.23786
[195]	train-mlogloss:0.29492	eval-mlogloss:0.23784
[196]	train-mlogloss:0.29492	eval-mlogloss:0.23784
[197]	train-mlogloss:0.29484	eval-mlogloss:0.23799
[198]	train-mlogloss:0.29473	eval-mlogloss:0.23773
[199]	train-mlogloss:0.29383	eval-mlogloss:0.23670
[200]	train-mlogloss:0.29361	eval-mlogloss:0.23667
[201]	train-mlogloss:0.29342	eval-mlogloss:0.23661
[202]	train-mlogloss:0.29343	eval-mlogloss:0.23660
[203]	train-mlogloss:0.29344	eval-mlogloss:0.23657
[204]	train-mlogloss:0.29320	eval-mlogloss:0.23640
[205]	train-mlogloss:0.29152	eval-mlogloss:0.23425
[206]	train-mlogloss:0.29153	eval-mlogloss:0.23418
[207]	train-mlogloss:0.29155	eval-mlogloss:0.23409
[208]	train-mlogloss:0.29142	eval-mlogloss:0.23411
[209]	train-mlogloss:0.29142	eval-mlogloss:0.23410
[210]	train-mlogloss:0.29134	eval-mlogloss:0.23404
[211]	train-mlogloss:0.29122	eval-mlogloss:0.23397
[212]	train-mlogloss:0.29110	eval-mlogloss:0.23390
[213]	train-mlogloss:0.29008	eval-mlogloss:0.23281
[214]	train-mlogloss:0.29008	eval-mlogloss:0.23285
[215]	train-mlogloss:0.29009	eval-mlogloss:0.23282
[216]	train-mlogloss:0.29008	eval-mlogloss:0.23287
[217]	train-mlogloss:0.29006	eval-mlogloss:0.23287
[218]	train-mlogloss:0.29006	eval-mlogloss:0.23282
[219]	train-mlogloss:0.29006	eval-mlogloss:0.23279
[220]	train-mlogloss:0.29008	eval-mlogloss:0.23277
[221]	train-mlogloss:0.29008	eval-mlogloss:0.23283
[222]	train-mlogloss:0.29005	eval-mlogloss:0.23289
[223]	train-mlogloss:0.28902	eval-mlogloss:0.23155
[224]	train-mlogloss:0.28898	eval-mlogloss:0.23142
[225]	train-mlogloss:0.28898	eval-mlogloss:0.23140
[226]	train-mlogloss:0.28892	eval-mlogloss:0.23125
[227]	train-mlogloss:0.28862	eval-mlogloss:0.23117
[228]	train-mlogloss:0.28739	eval-mlogloss:0.22940
[229]	train-mlogloss:0.28616	eval-mlogloss:0.22793
[230]	train-mlogloss:0.28616	eval-mlogloss:0.22789
[231]	train-mlogloss:0.28589	eval-mlogloss:0.22756
[232]	train-mlogloss:0.28590	eval-mlogloss:0.22761
[233]	train-mlogloss:0.28577	eval-mlogloss:0.22749
[234]	train-mlogloss:0.28577	eval-mlogloss:0.22752
[235]	train-mlogloss:0.28579	eval-mlogloss:0.22749
[236]	train-mlogloss:0.28580	eval-mlogloss:0.22744
[237]	train-mlogloss:0.28579	eval-mlogloss:0.22748
[238]	train-mlogloss:0.28575	eval-mlogloss:0.22738
[239]	train-mlogloss:0.28576	eval-mlogloss:0.22732
[240]	train-mlogloss:0.28578	eval-mlogloss:0.22728
[241]	train-mlogloss:0.28579	eval-mlogloss:0.22724
[242]	train-mlogloss:0.28572	eval-mlogloss:0.22717
[243]	train-mlogloss:0.28566	eval-mlogloss:0.22696
[244]	train-mlogloss:0.28565	eval-mlogloss:0.22700
[245]	train-mlogloss:0.28556	eval-mlogloss:0.22673
[246]	train-mlogloss:0.28557	eval-mlogloss:0.22677
[247]	train-mlogloss:0.28553	eval-mlogloss:0.22678
[248]	train-mlogloss:0.28543	eval-mlogloss:0.22644
[249]	train-mlogloss:0.28543	eval-mlogloss:0.22643
[250]	train-mlogloss:0.28544	eval-mlogloss:0.22640
[251]	train-mlogloss:0.28543	eval-mlogloss:0.22643
[252]	train-mlogloss:0.28544	eval-mlogloss:0.22640
[253]	train-mlogloss:0.28546	eval-mlogloss:0.22634
[254]	train-mlogloss:0.28552	eval-mlogloss:0.22638
[255]	train-mlogloss:0.28554	eval-mlogloss:0.22635
[256]	train-mlogloss:0.28553	eval-mlogloss:0.22634
[257]	train-mlogloss:0.28545	eval-mlogloss:0.22626
[258]	train-mlogloss:0.28522	eval-mlogloss:0.22623
[259]	train-mlogloss:0.28491	eval-mlogloss:0.22590
[260]	train-mlogloss:0.28482	eval-mlogloss:0.22589
[261]	train-mlogloss:0.28481	eval-mlogloss:0.22589
[262]	train-mlogloss:0.28477	eval-mlogloss:0.22575
[263]	train-mlogloss:0.28432	eval-mlogloss:0.22518
[264]	train-mlogloss:0.28431	eval-mlogloss:0.22522
[265]	train-mlogloss:0.28430	eval-mlogloss:0.22529
[266]	train-mlogloss:0.28431	eval-mlogloss:0.22529
[267]	train-mlogloss:0.28421	eval-mlogloss:0.22514
[268]	train-mlogloss:0.28421	eval-mlogloss:0.22516
[269]	train-mlogloss:0.28420	eval-mlogloss:0.22520
[270]	train-mlogloss:0.28294	eval-mlogloss:0.22348
[271]	train-mlogloss:0.28292	eval-mlogloss:0.22355
[272]	train-mlogloss:0.28280	eval-mlogloss:0.22297
[273]	train-mlogloss:0.28263	eval-mlogloss:0.22280
[274]	train-mlogloss:0.28269	eval-mlogloss:0.22286
[275]	train-mlogloss:0.28162	eval-mlogloss:0.22164
[276]	train-mlogloss:0.28162	eval-mlogloss:0.22160
[277]	train-mlogloss:0.28161	eval-mlogloss:0.22161
[278]	train-mlogloss:0.28163	eval-mlogloss:0.22152
[279]	train-mlogloss:0.28161	eval-mlogloss:0.22158
[280]	train-mlogloss:0.28160	eval-mlogloss:0.22160
[281]	train-mlogloss:0.28160	eval-mlogloss:0.22161
[282]	train-mlogloss:0.28160	eval-mlogloss:0.22158
[283]	train-mlogloss:0.28158	eval-mlogloss:0.22149
[284]	train-mlogloss:0.28158	eval-mlogloss:0.22149
[285]	train-mlogloss:0.28161	eval-mlogloss:0.22143
[286]	train-mlogloss:0.28161	eval-mlogloss:0.22144
[287]	train-mlogloss:0.28158	eval-mlogloss:0.22156
[288]	train-mlogloss:0.28157	eval-mlogloss:0.22158
[289]	train-mlogloss:0.28155	eval-mlogloss:0.22161
[290]	train-mlogloss:0.28154	eval-mlogloss:0.22165
[291]	train-mlogloss:0.28149	eval-mlogloss:0.22163
[292]	train-mlogloss:0.28141	eval-mlogloss:0.22114
[293]	train-mlogloss:0.28142	eval-mlogloss:0.22111
[294]	train-mlogloss:0.28141	eval-mlogloss:0.22115
[295]	train-mlogloss:0.28137	eval-mlogloss:0.22113
[296]	train-mlogloss:0.28136	eval-mlogloss:0.22119
[297]	train-mlogloss:0.28131	eval-mlogloss:0.22096
[298]	train-mlogloss:0.28130	eval-mlogloss:0.22100
[299]	train-mlogloss:0.28113	eval-mlogloss:0.22078

[I 2026-09-28 23:31:28,747] Trial 4 finished with value: 1.0 and parameters: {'lambda': 0.02665689586743912, 'alpha': 0.00010444316141810673, 'eta': 0.02765788729091418, 'gamma': 0.11567257214577926, 'max_depth': 9, 'min_child_weight': 7, 'subsample': 0.47832615699749115, 'colsample_bytree': 0.40606979650506636}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.03495	eval-mlogloss:1.03211

[I 2026-09-28 23:31:28,786] Trial 5 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.01055	eval-mlogloss:1.00835

[I 2026-09-28 23:31:28,849] Trial 6 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.82733	eval-mlogloss:0.81370

[I 2026-09-28 23:31:28,905] Trial 7 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.01173	eval-mlogloss:1.01072

[I 2026-09-28 23:31:28,982] Trial 8 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.07974	eval-mlogloss:1.08075
[1]	train-mlogloss:1.05652	eval-mlogloss:1.05628
[2]	train-mlogloss:1.03774	eval-mlogloss:1.03633
[3]	train-mlogloss:1.02166	eval-mlogloss:1.02003
[4]	train-mlogloss:1.00021	eval-mlogloss:0.99752
[5]	train-mlogloss:0.97909	eval-mlogloss:0.97460
[6]	train-mlogloss:0.96584	eval-mlogloss:0.96131
[7]	train-mlogloss:0.95278	eval-mlogloss:0.94807
[8]	train-mlogloss:0.93702	eval-mlogloss:0.93202
[9]	train-mlogloss:0.92197	eval-mlogloss:0.91638
[10]	train-mlogloss:0.90849	eval-mlogloss:0.90260
[11]	train-mlogloss:0.89160	eval-mlogloss:0.88364
[12]	train-mlogloss:0.87783	eval-mlogloss:0.86897
[13]	train-mlogloss:0.86789	eval-mlogloss:0.85826
[14]	train-mlogloss:0.85433	eval-mlogloss:0.84386
[15]	train-mlogloss:0.83920	eval-mlogloss:0.82765
[16]	train-mlogloss:0.82655	eval-mlogloss:0.81404
[17]	train-mlogloss:0.81085	eval-mlogloss:0.79778
[18]	train-mlogloss:0.79907	eval-mlogloss:0.78588
[19]	train-mlogloss:0.78846	eval-mlogloss:0.77379
[20]	train-mlogloss:0.77684	eval-mlogloss:0.76158
[21]	train-mlogloss:0.76231	eval-mlogloss:0.74619
[22]	train-mlogloss:0.75195	eval-mlogloss:0.73487
[23]	train-mlogloss:0.74218	eval-mlogloss:0.72462
[24]	train-mlogloss:0.73256	eval-mlogloss:0.71442
[25]	train-mlogloss:0.72243	eval-mlogloss:0.70369
[26]	train-mlogloss:0.70905	eval-mlogloss:0.68936
[27]	train-mlogloss:0.69582	eval-mlogloss:0.67553
[28]	train-mlogloss:0.68434	eval-mlogloss:0.66237
[29]	train-mlogloss:0.67289	eval-mlogloss:0.64988
[30]	train-mlogloss:0.66502	eval-mlogloss:0.64121
[31]	train-mlogloss:0.65518	eval-mlogloss:0.63062
[32]	train-mlogloss:0.64437	eval-mlogloss:0.61902
[33]	train-mlogloss:0.63383	eval-mlogloss:0.60717
[34]	train-mlogloss:0.62467	eval-mlogloss:0.59705
[35]	train-mlogloss:0.61720	eval-mlogloss:0.58845
[36]	train-mlogloss:0.61046	eval-mlogloss:0.58174
[37]	train-mlogloss:0.60266	eval-mlogloss:0.57352
[38]	train-mlogloss:0.59450	eval-mlogloss:0.56425
[39]	train-mlogloss:0.58955	eval-mlogloss:0.55861
[40]	train-mlogloss:0.58238	eval-mlogloss:0.55066
[41]	train-mlogloss:0.57519	eval-mlogloss:0.54315
[42]	train-mlogloss:0.56865	eval-mlogloss:0.53668
[43]	train-mlogloss:0.56305	eval-mlogloss:0.53041
[44]	train-mlogloss:0.55649	eval-mlogloss:0.52338
[45]	train-mlogloss:0.55096	eval-mlogloss:0.51719
[46]	train-mlogloss:0.54470	eval-mlogloss:0.51013
[47]	train-mlogloss:0.53871	eval-mlogloss:0.50393
[48]	train-mlogloss:0.53367	eval-mlogloss:0.49908
[49]	train-mlogloss:0.52854	eval-mlogloss:0.49313
[50]	train-mlogloss:0.52372	eval-mlogloss:0.48806
[51]	train-mlogloss:0.51946	eval-mlogloss:0.48364
[52]	train-mlogloss:0.51200	eval-mlogloss:0.47551
[53]	train-mlogloss:0.50711	eval-mlogloss:0.47029
[54]	train-mlogloss:0.50163	eval-mlogloss:0.46443
[55]	train-mlogloss:0.49559	eval-mlogloss:0.45717
[56]	train-mlogloss:0.49165	eval-mlogloss:0.45286
[57]	train-mlogloss:0.48698	eval-mlogloss:0.44784
[58]	train-mlogloss:0.48178	eval-mlogloss:0.44203
[59]	train-mlogloss:0.47696	eval-mlogloss:0.43699
[60]	train-mlogloss:0.47284	eval-mlogloss:0.43185
[61]	train-mlogloss:0.46931	eval-mlogloss:0.42808
[62]	train-mlogloss:0.46492	eval-mlogloss:0.42277
[63]	train-mlogloss:0.46077	eval-mlogloss:0.41841
[64]	train-mlogloss:0.45815	eval-mlogloss:0.41542
[65]	train-mlogloss:0.45485	eval-mlogloss:0.41166
[66]	train-mlogloss:0.45087	eval-mlogloss:0.40723
[67]	train-mlogloss:0.44792	eval-mlogloss:0.40428
[68]	train-mlogloss:0.44481	eval-mlogloss:0.40116
[69]	train-mlogloss:0.44187	eval-mlogloss:0.39787
[70]	train-mlogloss:0.43912	eval-mlogloss:0.39489
[71]	train-mlogloss:0.43717	eval-mlogloss:0.39275
[72]	train-mlogloss:0.43253	eval-mlogloss:0.38819
[73]	train-mlogloss:0.43195	eval-mlogloss:0.38741
[74]	train-mlogloss:0.42765	eval-mlogloss:0.38274
[75]	train-mlogloss:0.42454	eval-mlogloss:0.37929
[76]	train-mlogloss:0.42043	eval-mlogloss:0.37499
[77]	train-mlogloss:0.41724	eval-mlogloss:0.37147
[78]	train-mlogloss:0.41543	eval-mlogloss:0.36924
[79]	train-mlogloss:0.41262	eval-mlogloss:0.36616
[80]	train-mlogloss:0.41220	eval-mlogloss:0.36561
[81]	train-mlogloss:0.41215	eval-mlogloss:0.36561
[82]	train-mlogloss:0.41024	eval-mlogloss:0.36291
[83]	train-mlogloss:0.40705	eval-mlogloss:0.35928
[84]	train-mlogloss:0.40524	eval-mlogloss:0.35727
[85]	train-mlogloss:0.40507	eval-mlogloss:0.35716
[86]	train-mlogloss:0.40174	eval-mlogloss:0.35333
[87]	train-mlogloss:0.40143	eval-mlogloss:0.35305
[88]	train-mlogloss:0.39978	eval-mlogloss:0.35118
[89]	train-mlogloss:0.39810	eval-mlogloss:0.34949
[90]	train-mlogloss:0.39730	eval-mlogloss:0.34880
[91]	train-mlogloss:0.39706	eval-mlogloss:0.34822
[92]	train-mlogloss:0.39617	eval-mlogloss:0.34661
[93]	train-mlogloss:0.39565	eval-mlogloss:0.34563
[94]	train-mlogloss:0.39555	eval-mlogloss:0.34574
[95]	train-mlogloss:0.39450	eval-mlogloss:0.34442
[96]	train-mlogloss:0.39287	eval-mlogloss:0.34256
[97]	train-mlogloss:0.39112	eval-mlogloss:0.34044
[98]	train-mlogloss:0.38998	eval-mlogloss:0.33915
[99]	train-mlogloss:0.38924	eval-mlogloss:0.33844
[100]	train-mlogloss:0.38857	eval-mlogloss:0.33776
[101]	train-mlogloss:0.38527	eval-mlogloss:0.33443
[102]	train-mlogloss:0.38518	eval-mlogloss:0.33424
[103]	train-mlogloss:0.38491	eval-mlogloss:0.33413
[104]	train-mlogloss:0.38423	eval-mlogloss:0.33333
[105]	train-mlogloss:0.38215	eval-mlogloss:0.33093
[106]	train-mlogloss:0.38052	eval-mlogloss:0.32906
[107]	train-mlogloss:0.37885	eval-mlogloss:0.32710
[108]	train-mlogloss:0.37870	eval-mlogloss:0.32689
[109]	train-mlogloss:0.37835	eval-mlogloss:0.32647
[110]	train-mlogloss:0.37817	eval-mlogloss:0.32609
[111]	train-mlogloss:0.37799	eval-mlogloss:0.32574
[112]	train-mlogloss:0.37675	eval-mlogloss:0.32442
[113]	train-mlogloss:0.37420	eval-mlogloss:0.32146
[114]	train-mlogloss:0.37347	eval-mlogloss:0.32050
[115]	train-mlogloss:0.37079	eval-mlogloss:0.31742
[116]	train-mlogloss:0.36960	eval-mlogloss:0.31614
[117]	train-mlogloss:0.36820	eval-mlogloss:0.31442
[118]	train-mlogloss:0.36541	eval-mlogloss:0.31152
[119]	train-mlogloss:0.36439	eval-mlogloss:0.31069
[120]	train-mlogloss:0.36435	eval-mlogloss:0.31070
[121]	train-mlogloss:0.36434	eval-mlogloss:0.31073
[122]	train-mlogloss:0.36400	eval-mlogloss:0.31037
[123]	train-mlogloss:0.36393	eval-mlogloss:0.31042
[124]	train-mlogloss:0.36393	eval-mlogloss:0.31042
[125]	train-mlogloss:0.36365	eval-mlogloss:0.31005
[126]	train-mlogloss:0.36349	eval-mlogloss:0.30992
[127]	train-mlogloss:0.36342	eval-mlogloss:0.30981
[128]	train-mlogloss:0.36202	eval-mlogloss:0.30821
[129]	train-mlogloss:0.36199	eval-mlogloss:0.30820
[130]	train-mlogloss:0.36057	eval-mlogloss:0.30633
[131]	train-mlogloss:0.35932	eval-mlogloss:0.30461
[132]	train-mlogloss:0.35925	eval-mlogloss:0.30451
[133]	train-mlogloss:0.35914	eval-mlogloss:0.30444
[134]	train-mlogloss:0.35906	eval-mlogloss:0.30422
[135]	train-mlogloss:0.35889	eval-mlogloss:0.30380
[136]	train-mlogloss:0.35879	eval-mlogloss:0.30380
[137]	train-mlogloss:0.35879	eval-mlogloss:0.30381
[138]	train-mlogloss:0.35772	eval-mlogloss:0.30230
[139]	train-mlogloss:0.35745	eval-mlogloss:0.30220
[140]	train-mlogloss:0.35631	eval-mlogloss:0.30055
[141]	train-mlogloss:0.35625	eval-mlogloss:0.30046
[142]	train-mlogloss:0.35625	eval-mlogloss:0.30051
[143]	train-mlogloss:0.35600	eval-mlogloss:0.30024
[144]	train-mlogloss:0.35562	eval-mlogloss:0.29959
[145]	train-mlogloss:0.35546	eval-mlogloss:0.29937
[146]	train-mlogloss:0.35536	eval-mlogloss:0.29919
[147]	train-mlogloss:0.35493	eval-mlogloss:0.29834
[148]	train-mlogloss:0.35492	eval-mlogloss:0.29838
[149]	train-mlogloss:0.35456	eval-mlogloss:0.29773
[150]	train-mlogloss:0.35450	eval-mlogloss:0.29771
[151]	train-mlogloss:0.35450	eval-mlogloss:0.29769
[152]	train-mlogloss:0.35431	eval-mlogloss:0.29750
[153]	train-mlogloss:0.35396	eval-mlogloss:0.29679
[154]	train-mlogloss:0.35375	eval-mlogloss:0.29659
[155]	train-mlogloss:0.35369	eval-mlogloss:0.29654
[156]	train-mlogloss:0.35239	eval-mlogloss:0.29495
[157]	train-mlogloss:0.35237	eval-mlogloss:0.29491
[158]	train-mlogloss:0.35234	eval-mlogloss:0.29492
[159]	train-mlogloss:0.35221	eval-mlogloss:0.29456
[160]	train-mlogloss:0.35213	eval-mlogloss:0.29434
[161]	train-mlogloss:0.35203	eval-mlogloss:0.29426
[162]	train-mlogloss:0.35194	eval-mlogloss:0.29404
[163]	train-mlogloss:0.35185	eval-mlogloss:0.29401
[164]	train-mlogloss:0.35033	eval-mlogloss:0.29257
[165]	train-mlogloss:0.35017	eval-mlogloss:0.29218
[166]	train-mlogloss:0.35008	eval-mlogloss:0.29210
[167]	train-mlogloss:0.34970	eval-mlogloss:0.29166
[168]	train-mlogloss:0.34947	eval-mlogloss:0.29155
[169]	train-mlogloss:0.34930	eval-mlogloss:0.29109
[170]	train-mlogloss:0.34924	eval-mlogloss:0.29103
[171]	train-mlogloss:0.34909	eval-mlogloss:0.29086
[172]	train-mlogloss:0.34801	eval-mlogloss:0.28951
[173]	train-mlogloss:0.34795	eval-mlogloss:0.28945
[174]	train-mlogloss:0.34786	eval-mlogloss:0.28939
[175]	train-mlogloss:0.34772	eval-mlogloss:0.28899
[176]	train-mlogloss:0.34756	eval-mlogloss:0.28891
[177]	train-mlogloss:0.34732	eval-mlogloss:0.28863
[178]	train-mlogloss:0.34725	eval-mlogloss:0.28858
[179]	train-mlogloss:0.34714	eval-mlogloss:0.28846
[180]	train-mlogloss:0.34711	eval-mlogloss:0.28842
[181]	train-mlogloss:0.34705	eval-mlogloss:0.28820
[182]	train-mlogloss:0.34701	eval-mlogloss:0.28823
[183]	train-mlogloss:0.34701	eval-mlogloss:0.28823
[184]	train-mlogloss:0.34690	eval-mlogloss:0.28794
[185]	train-mlogloss:0.34688	eval-mlogloss:0.28797
[186]	train-mlogloss:0.34683	eval-mlogloss:0.28797
[187]	train-mlogloss:0.34676	eval-mlogloss:0.28796
[188]	train-mlogloss:0.34669	eval-mlogloss:0.28806
[189]	train-mlogloss:0.34652	eval-mlogloss:0.28757
[190]	train-mlogloss:0.34646	eval-mlogloss:0.28749
[191]	train-mlogloss:0.34639	eval-mlogloss:0.28727
[192]	train-mlogloss:0.34630	eval-mlogloss:0.28700
[193]	train-mlogloss:0.34623	eval-mlogloss:0.28696
[194]	train-mlogloss:0.34614	eval-mlogloss:0.28674
[195]	train-mlogloss:0.34606	eval-mlogloss:0.28672
[196]	train-mlogloss:0.34603	eval-mlogloss:0.28668
[197]	train-mlogloss:0.34598	eval-mlogloss:0.28676
[198]	train-mlogloss:0.34594	eval-mlogloss:0.28670
[199]	train-mlogloss:0.34506	eval-mlogloss:0.28572
[200]	train-mlogloss:0.34506	eval-mlogloss:0.28571
[201]	train-mlogloss:0.34497	eval-mlogloss:0.28567
[202]	train-mlogloss:0.34481	eval-mlogloss:0.28561
[203]	train-mlogloss:0.34476	eval-mlogloss:0.28571
[204]	train-mlogloss:0.34463	eval-mlogloss:0.28567
[205]	train-mlogloss:0.34349	eval-mlogloss:0.28438
[206]	train-mlogloss:0.34345	eval-mlogloss:0.28425
[207]	train-mlogloss:0.34340	eval-mlogloss:0.28421
[208]	train-mlogloss:0.34321	eval-mlogloss:0.28399
[209]	train-mlogloss:0.34318	eval-mlogloss:0.28395
[210]	train-mlogloss:0.34313	eval-mlogloss:0.28396
[211]	train-mlogloss:0.34305	eval-mlogloss:0.28393
[212]	train-mlogloss:0.34297	eval-mlogloss:0.28390
[213]	train-mlogloss:0.34207	eval-mlogloss:0.28257
[214]	train-mlogloss:0.34200	eval-mlogloss:0.28255
[215]	train-mlogloss:0.34194	eval-mlogloss:0.28245
[216]	train-mlogloss:0.34195	eval-mlogloss:0.28248
[217]	train-mlogloss:0.34192	eval-mlogloss:0.28241
[218]	train-mlogloss:0.34187	eval-mlogloss:0.28238
[219]	train-mlogloss:0.34178	eval-mlogloss:0.28232
[220]	train-mlogloss:0.34178	eval-mlogloss:0.28231
[221]	train-mlogloss:0.34173	eval-mlogloss:0.28229
[222]	train-mlogloss:0.34172	eval-mlogloss:0.28230
[223]	train-mlogloss:0.34051	eval-mlogloss:0.28095
[224]	train-mlogloss:0.34042	eval-mlogloss:0.28090
[225]	train-mlogloss:0.34035	eval-mlogloss:0.28084
[226]	train-mlogloss:0.34034	eval-mlogloss:0.28083
[227]	train-mlogloss:0.34027	eval-mlogloss:0.28077
[228]	train-mlogloss:0.33926	eval-mlogloss:0.27938
[229]	train-mlogloss:0.33927	eval-mlogloss:0.27938
[230]	train-mlogloss:0.33923	eval-mlogloss:0.27930
[231]	train-mlogloss:0.33912	eval-mlogloss:0.27922
[232]	train-mlogloss:0.33904	eval-mlogloss:0.27921
[233]	train-mlogloss:0.33892	eval-mlogloss:0.27912
[234]	train-mlogloss:0.33893	eval-mlogloss:0.27914
[235]	train-mlogloss:0.33887	eval-mlogloss:0.27907
[236]	train-mlogloss:0.33877	eval-mlogloss:0.27880
[237]	train-mlogloss:0.33786	eval-mlogloss:0.27791
[238]	train-mlogloss:0.33775	eval-mlogloss:0.27754
[239]	train-mlogloss:0.33771	eval-mlogloss:0.27748
[240]	train-mlogloss:0.33771	eval-mlogloss:0.27747
[241]	train-mlogloss:0.33666	eval-mlogloss:0.27613
[242]	train-mlogloss:0.33666	eval-mlogloss:0.27612
[243]	train-mlogloss:0.33662	eval-mlogloss:0.27599
[244]	train-mlogloss:0.33648	eval-mlogloss:0.27593
[245]	train-mlogloss:0.33634	eval-mlogloss:0.27555
[246]	train-mlogloss:0.33634	eval-mlogloss:0.27558
[247]	train-mlogloss:0.33629	eval-mlogloss:0.27563
[248]	train-mlogloss:0.33617	eval-mlogloss:0.27524
[249]	train-mlogloss:0.33612	eval-mlogloss:0.27529
[250]	train-mlogloss:0.33613	eval-mlogloss:0.27529
[251]	train-mlogloss:0.33605	eval-mlogloss:0.27527
[252]	train-mlogloss:0.33605	eval-mlogloss:0.27518
[253]	train-mlogloss:0.33600	eval-mlogloss:0.27507
[254]	train-mlogloss:0.33599	eval-mlogloss:0.27505
[255]	train-mlogloss:0.33598	eval-mlogloss:0.27503
[256]	train-mlogloss:0.33594	eval-mlogloss:0.27503
[257]	train-mlogloss:0.33588	eval-mlogloss:0.27486
[258]	train-mlogloss:0.33581	eval-mlogloss:0.27485
[259]	train-mlogloss:0.33573	eval-mlogloss:0.27481
[260]	train-mlogloss:0.33567	eval-mlogloss:0.27478
[261]	train-mlogloss:0.33560	eval-mlogloss:0.27468
[262]	train-mlogloss:0.33556	eval-mlogloss:0.27458
[263]	train-mlogloss:0.33541	eval-mlogloss:0.27448
[264]	train-mlogloss:0.33456	eval-mlogloss:0.27337
[265]	train-mlogloss:0.33449	eval-mlogloss:0.27336
[266]	train-mlogloss:0.33449	eval-mlogloss:0.27335
[267]	train-mlogloss:0.33449	eval-mlogloss:0.27336
[268]	train-mlogloss:0.33450	eval-mlogloss:0.27339
[269]	train-mlogloss:0.33450	eval-mlogloss:0.27341
[270]	train-mlogloss:0.33442	eval-mlogloss:0.27316
[271]	train-mlogloss:0.33441	eval-mlogloss:0.27320
[272]	train-mlogloss:0.33440	eval-mlogloss:0.27319
[273]	train-mlogloss:0.33429	eval-mlogloss:0.27313
[274]	train-mlogloss:0.33430	eval-mlogloss:0.27312
[275]	train-mlogloss:0.33430	eval-mlogloss:0.27312
[276]	train-mlogloss:0.33430	eval-mlogloss:0.27311
[277]	train-mlogloss:0.33430	eval-mlogloss:0.27309
[278]	train-mlogloss:0.33319	eval-mlogloss:0.27182
[279]	train-mlogloss:0.33319	eval-mlogloss:0.27182
[280]	train-mlogloss:0.33313	eval-mlogloss:0.27183
[281]	train-mlogloss:0.33310	eval-mlogloss:0.27174
[282]	train-mlogloss:0.33306	eval-mlogloss:0.27157
[283]	train-mlogloss:0.33300	eval-mlogloss:0.27142
[284]	train-mlogloss:0.33294	eval-mlogloss:0.27137
[285]	train-mlogloss:0.33294	eval-mlogloss:0.27139
[286]	train-mlogloss:0.33294	eval-mlogloss:0.27140
[287]	train-mlogloss:0.33291	eval-mlogloss:0.27131
[288]	train-mlogloss:0.33287	eval-mlogloss:0.27128
[289]	train-mlogloss:0.33287	eval-mlogloss:0.27126
[290]	train-mlogloss:0.33274	eval-mlogloss:0.27090
[291]	train-mlogloss:0.33269	eval-mlogloss:0.27087
[292]	train-mlogloss:0.33250	eval-mlogloss:0.27035
[293]	train-mlogloss:0.33250	eval-mlogloss:0.27035
[294]	train-mlogloss:0.33251	eval-mlogloss:0.27034
[295]	train-mlogloss:0.33244	eval-mlogloss:0.27033
[296]	train-mlogloss:0.33235	eval-mlogloss:0.27027
[297]	train-mlogloss:0.33230	eval-mlogloss:0.27029
[298]	train-mlogloss:0.33229	eval-mlogloss:0.27031
[299]	train-mlogloss:0.33223	eval-mlogloss:0.27026

[I 2026-09-28 23:31:33,744] Trial 9 finished with value: 1.0 and parameters: {'lambda': 5.758783735044555e-05, 'alpha': 0.32879931981673405, 'eta': 0.019599213446184673, 'gamma': 1.0067046776271836e-06, 'max_depth': 9, 'min_child_weight': 10, 'subsample': 0.6013863374361386, 'colsample_bytree': 0.719956887100206}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.79960	eval-mlogloss:0.78196

[I 2026-09-28 23:31:33,809] Trial 10 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03885	eval-mlogloss:1.03738

[I 2026-09-28 23:31:33,877] Trial 11 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.88977	eval-mlogloss:0.87905

[I 2026-09-28 23:31:33,967] Trial 12 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.77675	eval-mlogloss:0.75573

[I 2026-09-28 23:31:34,028] Trial 13 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.01950	eval-mlogloss:1.01084

[I 2026-09-28 23:31:34,119] Trial 14 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.79855	eval-mlogloss:0.78003

[I 2026-09-28 23:31:34,192] Trial 15 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.87451	eval-mlogloss:0.87042

[I 2026-09-28 23:31:34,251] Trial 16 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03880	eval-mlogloss:1.03736

[I 2026-09-28 23:31:34,332] Trial 17 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.81688	eval-mlogloss:0.80960

[I 2026-09-28 23:31:34,399] Trial 18 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.92976	eval-mlogloss:0.92581

[I 2026-09-28 23:31:34,483] Trial 19 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.99414	eval-mlogloss:0.99356

[I 2026-09-28 23:31:34,553] Trial 20 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.02314	eval-mlogloss:1.01489

[I 2026-09-28 23:31:34,621] Trial 21 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03145	eval-mlogloss:1.03307

[I 2026-09-28 23:31:34,691] Trial 22 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.97811	eval-mlogloss:0.97940

[I 2026-09-28 23:31:34,780] Trial 23 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.07784	eval-mlogloss:1.07965
[1]	train-mlogloss:1.05848	eval-mlogloss:1.05959
[2]	train-mlogloss:1.04226	eval-mlogloss:1.04265
[3]	train-mlogloss:1.02390	eval-mlogloss:1.02269
[4]	train-mlogloss:1.00536	eval-mlogloss:1.00320
[5]	train-mlogloss:0.98642	eval-mlogloss:0.98300
[6]	train-mlogloss:0.97224	eval-mlogloss:0.96847
[7]	train-mlogloss:0.96050	eval-mlogloss:0.95685
[8]	train-mlogloss:0.94462	eval-mlogloss:0.94017
[9]	train-mlogloss:0.92783	eval-mlogloss:0.92275
[10]	train-mlogloss:0.91554	eval-mlogloss:0.90972
[11]	train-mlogloss:0.90315	eval-mlogloss:0.89687
[12]	train-mlogloss:0.89105	eval-mlogloss:0.88402
[13]	train-mlogloss:0.88138	eval-mlogloss:0.87395
[14]	train-mlogloss:0.86901	eval-mlogloss:0.86113
[15]	train-mlogloss:0.85569	eval-mlogloss:0.84693
[16]	train-mlogloss:0.84436	eval-mlogloss:0.83522
[17]	train-mlogloss:0.83047	eval-mlogloss:0.82047
[18]	train-mlogloss:0.81956	eval-mlogloss:0.80931
[19]	train-mlogloss:0.80601	eval-mlogloss:0.79421
[20]	train-mlogloss:0.79553	eval-mlogloss:0.78309
[21]	train-mlogloss:0.78288	eval-mlogloss:0.76977
[22]	train-mlogloss:0.77306	eval-mlogloss:0.75903
[23]	train-mlogloss:0.76120	eval-mlogloss:0.74618
[24]	train-mlogloss:0.75131	eval-mlogloss:0.73609
[25]	train-mlogloss:0.73890	eval-mlogloss:0.72327
[26]	train-mlogloss:0.72632	eval-mlogloss:0.70918
[27]	train-mlogloss:0.71412	eval-mlogloss:0.69624
[28]	train-mlogloss:0.70331	eval-mlogloss:0.68438
[29]	train-mlogloss:0.69234	eval-mlogloss:0.67288
[30]	train-mlogloss:0.68322	eval-mlogloss:0.66254
[31]	train-mlogloss:0.67342	eval-mlogloss:0.65255
[32]	train-mlogloss:0.66384	eval-mlogloss:0.64284
[33]	train-mlogloss:0.65401	eval-mlogloss:0.63175
[34]	train-mlogloss:0.64389	eval-mlogloss:0.62067
[35]	train-mlogloss:0.63616	eval-mlogloss:0.61236
[36]	train-mlogloss:0.63016	eval-mlogloss:0.60625
[37]	train-mlogloss:0.62285	eval-mlogloss:0.59830
[38]	train-mlogloss:0.61438	eval-mlogloss:0.58924
[39]	train-mlogloss:0.60706	eval-mlogloss:0.58163
[40]	train-mlogloss:0.59895	eval-mlogloss:0.57255
[41]	train-mlogloss:0.59098	eval-mlogloss:0.56356
[42]	train-mlogloss:0.58282	eval-mlogloss:0.55458
[43]	train-mlogloss:0.57746	eval-mlogloss:0.54894
[44]	train-mlogloss:0.57126	eval-mlogloss:0.54320
[45]	train-mlogloss:0.56594	eval-mlogloss:0.53770
[46]	train-mlogloss:0.55828	eval-mlogloss:0.52891
[47]	train-mlogloss:0.55053	eval-mlogloss:0.52085
[48]	train-mlogloss:0.54358	eval-mlogloss:0.51421
[49]	train-mlogloss:0.53542	eval-mlogloss:0.50509
[50]	train-mlogloss:0.52984	eval-mlogloss:0.49897
[51]	train-mlogloss:0.52469	eval-mlogloss:0.49344
[52]	train-mlogloss:0.51732	eval-mlogloss:0.48544
[53]	train-mlogloss:0.51269	eval-mlogloss:0.48025
[54]	train-mlogloss:0.50721	eval-mlogloss:0.47461
[55]	train-mlogloss:0.50001	eval-mlogloss:0.46648
[56]	train-mlogloss:0.49620	eval-mlogloss:0.46228
[57]	train-mlogloss:0.49171	eval-mlogloss:0.45749
[58]	train-mlogloss:0.48674	eval-mlogloss:0.45170
[59]	train-mlogloss:0.48167	eval-mlogloss:0.44591
[60]	train-mlogloss:0.47585	eval-mlogloss:0.43913
[61]	train-mlogloss:0.47156	eval-mlogloss:0.43469
[62]	train-mlogloss:0.46703	eval-mlogloss:0.42942
[63]	train-mlogloss:0.46253	eval-mlogloss:0.42448
[64]	train-mlogloss:0.45854	eval-mlogloss:0.42050
[65]	train-mlogloss:0.45526	eval-mlogloss:0.41673
[66]	train-mlogloss:0.45127	eval-mlogloss:0.41214
[67]	train-mlogloss:0.44830	eval-mlogloss:0.40895
[68]	train-mlogloss:0.44511	eval-mlogloss:0.40567
[69]	train-mlogloss:0.44158	eval-mlogloss:0.40178
[70]	train-mlogloss:0.43873	eval-mlogloss:0.39888
[71]	train-mlogloss:0.43583	eval-mlogloss:0.39536
[72]	train-mlogloss:0.43158	eval-mlogloss:0.39114
[73]	train-mlogloss:0.42899	eval-mlogloss:0.38822
[74]	train-mlogloss:0.42509	eval-mlogloss:0.38389
[75]	train-mlogloss:0.42199	eval-mlogloss:0.38031
[76]	train-mlogloss:0.41819	eval-mlogloss:0.37629
[77]	train-mlogloss:0.41492	eval-mlogloss:0.37290
[78]	train-mlogloss:0.41132	eval-mlogloss:0.36886
[79]	train-mlogloss:0.40871	eval-mlogloss:0.36598
[80]	train-mlogloss:0.40712	eval-mlogloss:0.36392
[81]	train-mlogloss:0.40418	eval-mlogloss:0.36064
[82]	train-mlogloss:0.40062	eval-mlogloss:0.35660
[83]	train-mlogloss:0.39758	eval-mlogloss:0.35318
[84]	train-mlogloss:0.39530	eval-mlogloss:0.35100
[85]	train-mlogloss:0.39374	eval-mlogloss:0.34922
[86]	train-mlogloss:0.39080	eval-mlogloss:0.34597
[87]	train-mlogloss:0.38888	eval-mlogloss:0.34412
[88]	train-mlogloss:0.38719	eval-mlogloss:0.34228
[89]	train-mlogloss:0.38292	eval-mlogloss:0.33736
[90]	train-mlogloss:0.38000	eval-mlogloss:0.33418
[91]	train-mlogloss:0.37755	eval-mlogloss:0.33116
[92]	train-mlogloss:0.37426	eval-mlogloss:0.32746
[93]	train-mlogloss:0.37142	eval-mlogloss:0.32428
[94]	train-mlogloss:0.36855	eval-mlogloss:0.32125
[95]	train-mlogloss:0.36644	eval-mlogloss:0.31879
[96]	train-mlogloss:0.36386	eval-mlogloss:0.31591
[97]	train-mlogloss:0.36095	eval-mlogloss:0.31332
[98]	train-mlogloss:0.35857	eval-mlogloss:0.31067
[99]	train-mlogloss:0.35626	eval-mlogloss:0.30806
[100]	train-mlogloss:0.35406	eval-mlogloss:0.30578
[101]	train-mlogloss:0.35155	eval-mlogloss:0.30309
[102]	train-mlogloss:0.35139	eval-mlogloss:0.30290
[103]	train-mlogloss:0.34863	eval-mlogloss:0.29962
[104]	train-mlogloss:0.34715	eval-mlogloss:0.29774
[105]	train-mlogloss:0.34436	eval-mlogloss:0.29440
[106]	train-mlogloss:0.34302	eval-mlogloss:0.29289
[107]	train-mlogloss:0.34191	eval-mlogloss:0.29149
[108]	train-mlogloss:0.34055	eval-mlogloss:0.29019
[109]	train-mlogloss:0.33958	eval-mlogloss:0.28927
[110]	train-mlogloss:0.33942	eval-mlogloss:0.28888
[111]	train-mlogloss:0.33928	eval-mlogloss:0.28858
[112]	train-mlogloss:0.33692	eval-mlogloss:0.28612
[113]	train-mlogloss:0.33505	eval-mlogloss:0.28386
[114]	train-mlogloss:0.33370	eval-mlogloss:0.28241
[115]	train-mlogloss:0.33138	eval-mlogloss:0.28022
[116]	train-mlogloss:0.32985	eval-mlogloss:0.27864
[117]	train-mlogloss:0.32853	eval-mlogloss:0.27700
[118]	train-mlogloss:0.32629	eval-mlogloss:0.27454
[119]	train-mlogloss:0.32489	eval-mlogloss:0.27304
[120]	train-mlogloss:0.32474	eval-mlogloss:0.27286
[121]	train-mlogloss:0.32475	eval-mlogloss:0.27294
[122]	train-mlogloss:0.32432	eval-mlogloss:0.27248
[123]	train-mlogloss:0.32420	eval-mlogloss:0.27237
[124]	train-mlogloss:0.32211	eval-mlogloss:0.27021
[125]	train-mlogloss:0.32202	eval-mlogloss:0.26993
[126]	train-mlogloss:0.32161	eval-mlogloss:0.26943
[127]	train-mlogloss:0.32137	eval-mlogloss:0.26909
[128]	train-mlogloss:0.32040	eval-mlogloss:0.26794
[129]	train-mlogloss:0.32030	eval-mlogloss:0.26768
[130]	train-mlogloss:0.31813	eval-mlogloss:0.26530
[131]	train-mlogloss:0.31706	eval-mlogloss:0.26375
[132]	train-mlogloss:0.31707	eval-mlogloss:0.26372
[133]	train-mlogloss:0.31686	eval-mlogloss:0.26361
[134]	train-mlogloss:0.31679	eval-mlogloss:0.26367
[135]	train-mlogloss:0.31567	eval-mlogloss:0.26235
[136]	train-mlogloss:0.31454	eval-mlogloss:0.26086
[137]	train-mlogloss:0.31243	eval-mlogloss:0.25841
[138]	train-mlogloss:0.31155	eval-mlogloss:0.25735
[139]	train-mlogloss:0.31142	eval-mlogloss:0.25729
[140]	train-mlogloss:0.30999	eval-mlogloss:0.25544
[141]	train-mlogloss:0.30920	eval-mlogloss:0.25450
[142]	train-mlogloss:0.30919	eval-mlogloss:0.25452
[143]	train-mlogloss:0.30895	eval-mlogloss:0.25423
[144]	train-mlogloss:0.30800	eval-mlogloss:0.25318
[145]	train-mlogloss:0.30786	eval-mlogloss:0.25317
[146]	train-mlogloss:0.30696	eval-mlogloss:0.25217
[147]	train-mlogloss:0.30556	eval-mlogloss:0.25048
[148]	train-mlogloss:0.30478	eval-mlogloss:0.24959
[149]	train-mlogloss:0.30446	eval-mlogloss:0.24907
[150]	train-mlogloss:0.30424	eval-mlogloss:0.24875
[151]	train-mlogloss:0.30398	eval-mlogloss:0.24836
[152]	train-mlogloss:0.30327	eval-mlogloss:0.24753
[153]	train-mlogloss:0.30187	eval-mlogloss:0.24593
[154]	train-mlogloss:0.30174	eval-mlogloss:0.24583
[155]	train-mlogloss:0.30175	eval-mlogloss:0.24582
[156]	train-mlogloss:0.30078	eval-mlogloss:0.24462
[157]	train-mlogloss:0.30074	eval-mlogloss:0.24458
[158]	train-mlogloss:0.29990	eval-mlogloss:0.24367
[159]	train-mlogloss:0.29989	eval-mlogloss:0.24364
[160]	train-mlogloss:0.29989	eval-mlogloss:0.24363
[161]	train-mlogloss:0.29973	eval-mlogloss:0.24313
[162]	train-mlogloss:0.29974	eval-mlogloss:0.24314
[163]	train-mlogloss:0.29962	eval-mlogloss:0.24307
[164]	train-mlogloss:0.29872	eval-mlogloss:0.24222
[165]	train-mlogloss:0.29863	eval-mlogloss:0.24194
[166]	train-mlogloss:0.29853	eval-mlogloss:0.24189
[167]	train-mlogloss:0.29777	eval-mlogloss:0.24102
[168]	train-mlogloss:0.29760	eval-mlogloss:0.24092
[169]	train-mlogloss:0.29750	eval-mlogloss:0.24061
[170]	train-mlogloss:0.29743	eval-mlogloss:0.24040
[171]	train-mlogloss:0.29730	eval-mlogloss:0.24024
[172]	train-mlogloss:0.29634	eval-mlogloss:0.23899
[173]	train-mlogloss:0.29541	eval-mlogloss:0.23787
[174]	train-mlogloss:0.29444	eval-mlogloss:0.23683
[175]	train-mlogloss:0.29436	eval-mlogloss:0.23657
[176]	train-mlogloss:0.29423	eval-mlogloss:0.23650
[177]	train-mlogloss:0.29401	eval-mlogloss:0.23614
[178]	train-mlogloss:0.29385	eval-mlogloss:0.23594
[179]	train-mlogloss:0.29369	eval-mlogloss:0.23575
[180]	train-mlogloss:0.29369	eval-mlogloss:0.23574
[181]	train-mlogloss:0.29369	eval-mlogloss:0.23571
[182]	train-mlogloss:0.29277	eval-mlogloss:0.23483
[183]	train-mlogloss:0.29277	eval-mlogloss:0.23484
[184]	train-mlogloss:0.29277	eval-mlogloss:0.23485
[185]	train-mlogloss:0.29278	eval-mlogloss:0.23482
[186]	train-mlogloss:0.29278	eval-mlogloss:0.23484
[187]	train-mlogloss:0.29197	eval-mlogloss:0.23372
[188]	train-mlogloss:0.29191	eval-mlogloss:0.23380
[189]	train-mlogloss:0.29179	eval-mlogloss:0.23338
[190]	train-mlogloss:0.29166	eval-mlogloss:0.23319
[191]	train-mlogloss:0.29166	eval-mlogloss:0.23319
[192]	train-mlogloss:0.29152	eval-mlogloss:0.23302
[193]	train-mlogloss:0.29143	eval-mlogloss:0.23298
[194]	train-mlogloss:0.29143	eval-mlogloss:0.23299
[195]	train-mlogloss:0.29143	eval-mlogloss:0.23299
[196]	train-mlogloss:0.29090	eval-mlogloss:0.23239
[197]	train-mlogloss:0.29085	eval-mlogloss:0.23245
[198]	train-mlogloss:0.29078	eval-mlogloss:0.23239
[199]	train-mlogloss:0.29010	eval-mlogloss:0.23168
[200]	train-mlogloss:0.29010	eval-mlogloss:0.23169
[201]	train-mlogloss:0.29010	eval-mlogloss:0.23169
[202]	train-mlogloss:0.29011	eval-mlogloss:0.23169
[203]	train-mlogloss:0.29000	eval-mlogloss:0.23165
[204]	train-mlogloss:0.28987	eval-mlogloss:0.23159
[205]	train-mlogloss:0.28920	eval-mlogloss:0.23081
[206]	train-mlogloss:0.28921	eval-mlogloss:0.23079
[207]	train-mlogloss:0.28921	eval-mlogloss:0.23076
[208]	train-mlogloss:0.28915	eval-mlogloss:0.23072
[209]	train-mlogloss:0.28915	eval-mlogloss:0.23072
[210]	train-mlogloss:0.28916	eval-mlogloss:0.23074
[211]	train-mlogloss:0.28895	eval-mlogloss:0.23050
[212]	train-mlogloss:0.28888	eval-mlogloss:0.23047
[213]	train-mlogloss:0.28830	eval-mlogloss:0.22967
[214]	train-mlogloss:0.28820	eval-mlogloss:0.22963
[215]	train-mlogloss:0.28750	eval-mlogloss:0.22879
[216]	train-mlogloss:0.28749	eval-mlogloss:0.22881
[217]	train-mlogloss:0.28749	eval-mlogloss:0.22880
[218]	train-mlogloss:0.28749	eval-mlogloss:0.22878
[219]	train-mlogloss:0.28741	eval-mlogloss:0.22873
[220]	train-mlogloss:0.28742	eval-mlogloss:0.22872
[221]	train-mlogloss:0.28742	eval-mlogloss:0.22875
[222]	train-mlogloss:0.28741	eval-mlogloss:0.22877
[223]	train-mlogloss:0.28678	eval-mlogloss:0.22793
[224]	train-mlogloss:0.28674	eval-mlogloss:0.22786
[225]	train-mlogloss:0.28674	eval-mlogloss:0.22785
[226]	train-mlogloss:0.28671	eval-mlogloss:0.22780
[227]	train-mlogloss:0.28662	eval-mlogloss:0.22774
[228]	train-mlogloss:0.28596	eval-mlogloss:0.22678
[229]	train-mlogloss:0.28589	eval-mlogloss:0.22655
[230]	train-mlogloss:0.28575	eval-mlogloss:0.22633
[231]	train-mlogloss:0.28559	eval-mlogloss:0.22614
[232]	train-mlogloss:0.28552	eval-mlogloss:0.22614
[233]	train-mlogloss:0.28551	eval-mlogloss:0.22611
[234]	train-mlogloss:0.28551	eval-mlogloss:0.22613
[235]	train-mlogloss:0.28541	eval-mlogloss:0.22602
[236]	train-mlogloss:0.28530	eval-mlogloss:0.22564
[237]	train-mlogloss:0.28519	eval-mlogloss:0.22552
[238]	train-mlogloss:0.28513	eval-mlogloss:0.22529
[239]	train-mlogloss:0.28514	eval-mlogloss:0.22527
[240]	train-mlogloss:0.28514	eval-mlogloss:0.22525
[241]	train-mlogloss:0.28439	eval-mlogloss:0.22424
[242]	train-mlogloss:0.28439	eval-mlogloss:0.22423
[243]	train-mlogloss:0.28439	eval-mlogloss:0.22424
[244]	train-mlogloss:0.28438	eval-mlogloss:0.22425
[245]	train-mlogloss:0.28431	eval-mlogloss:0.22405
[246]	train-mlogloss:0.28432	eval-mlogloss:0.22408
[247]	train-mlogloss:0.28424	eval-mlogloss:0.22414
[248]	train-mlogloss:0.28417	eval-mlogloss:0.22391
[249]	train-mlogloss:0.28417	eval-mlogloss:0.22390
[250]	train-mlogloss:0.28418	eval-mlogloss:0.22389
[251]	train-mlogloss:0.28410	eval-mlogloss:0.22387
[252]	train-mlogloss:0.28411	eval-mlogloss:0.22386
[253]	train-mlogloss:0.28317	eval-mlogloss:0.22259
[254]	train-mlogloss:0.28317	eval-mlogloss:0.22260
[255]	train-mlogloss:0.28318	eval-mlogloss:0.22259

[I 2026-09-28 23:31:38,591] Trial 24 pruned. Trial was pruned at iteration 256.

[0]	train-mlogloss:1.04298	eval-mlogloss:1.04549
[1]	train-mlogloss:0.99578	eval-mlogloss:0.99669
[2]	train-mlogloss:0.98162	eval-mlogloss:0.98416
[3]	train-mlogloss:0.95797	eval-mlogloss:0.95796

[I 2026-09-28 23:31:38,696] Trial 25 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.08342	eval-mlogloss:1.08543
[1]	train-mlogloss:1.06832	eval-mlogloss:1.07002
[2]	train-mlogloss:1.05348	eval-mlogloss:1.05444
[3]	train-mlogloss:1.03953	eval-mlogloss:1.03983
[4]	train-mlogloss:1.02547	eval-mlogloss:1.02534
[5]	train-mlogloss:1.01153	eval-mlogloss:1.00993
[6]	train-mlogloss:0.99826	eval-mlogloss:0.99534
[7]	train-mlogloss:0.98859	eval-mlogloss:0.98554
[8]	train-mlogloss:0.97531	eval-mlogloss:0.97156
[9]	train-mlogloss:0.96223	eval-mlogloss:0.95813
[10]	train-mlogloss:0.95263	eval-mlogloss:0.94772
[11]	train-mlogloss:0.94124	eval-mlogloss:0.93588
[12]	train-mlogloss:0.93161	eval-mlogloss:0.92546
[13]	train-mlogloss:0.92252	eval-mlogloss:0.91604
[14]	train-mlogloss:0.91276	eval-mlogloss:0.90557
[15]	train-mlogloss:0.90163	eval-mlogloss:0.89376
[16]	train-mlogloss:0.89248	eval-mlogloss:0.88471
[17]	train-mlogloss:0.88122	eval-mlogloss:0.87291
[18]	train-mlogloss:0.87233	eval-mlogloss:0.86380
[19]	train-mlogloss:0.86137	eval-mlogloss:0.85196
[20]	train-mlogloss:0.85264	eval-mlogloss:0.84241
[21]	train-mlogloss:0.84203	eval-mlogloss:0.83164
[22]	train-mlogloss:0.83382	eval-mlogloss:0.82257
[23]	train-mlogloss:0.82381	eval-mlogloss:0.81232
[24]	train-mlogloss:0.81374	eval-mlogloss:0.80197
[25]	train-mlogloss:0.80366	eval-mlogloss:0.79158
[26]	train-mlogloss:0.79336	eval-mlogloss:0.78010
[27]	train-mlogloss:0.78312	eval-mlogloss:0.76931
[28]	train-mlogloss:0.77387	eval-mlogloss:0.75936
[29]	train-mlogloss:0.76464	eval-mlogloss:0.74999
[30]	train-mlogloss:0.75565	eval-mlogloss:0.74019
[31]	train-mlogloss:0.74714	eval-mlogloss:0.73116
[32]	train-mlogloss:0.73843	eval-mlogloss:0.72206
[33]	train-mlogloss:0.72935	eval-mlogloss:0.71244
[34]	train-mlogloss:0.72073	eval-mlogloss:0.70314
[35]	train-mlogloss:0.71230	eval-mlogloss:0.69393
[36]	train-mlogloss:0.70404	eval-mlogloss:0.68532
[37]	train-mlogloss:0.69744	eval-mlogloss:0.67865
[38]	train-mlogloss:0.68992	eval-mlogloss:0.67080
[39]	train-mlogloss:0.68317	eval-mlogloss:0.66336
[40]	train-mlogloss:0.67570	eval-mlogloss:0.65567
[41]	train-mlogloss:0.66786	eval-mlogloss:0.64748
[42]	train-mlogloss:0.65998	eval-mlogloss:0.63892
[43]	train-mlogloss:0.65350	eval-mlogloss:0.63214
[44]	train-mlogloss:0.64780	eval-mlogloss:0.62634
[45]	train-mlogloss:0.64142	eval-mlogloss:0.61959
[46]	train-mlogloss:0.63377	eval-mlogloss:0.61111
[47]	train-mlogloss:0.62670	eval-mlogloss:0.60367
[48]	train-mlogloss:0.61938	eval-mlogloss:0.59573
[49]	train-mlogloss:0.61249	eval-mlogloss:0.58805
[50]	train-mlogloss:0.60663	eval-mlogloss:0.58199
[51]	train-mlogloss:0.60041	eval-mlogloss:0.57539
[52]	train-mlogloss:0.59371	eval-mlogloss:0.56836
[53]	train-mlogloss:0.58776	eval-mlogloss:0.56193
[54]	train-mlogloss:0.58130	eval-mlogloss:0.55492
[55]	train-mlogloss:0.57473	eval-mlogloss:0.54771
[56]	train-mlogloss:0.56955	eval-mlogloss:0.54225
[57]	train-mlogloss:0.56363	eval-mlogloss:0.53610
[58]	train-mlogloss:0.55727	eval-mlogloss:0.52919
[59]	train-mlogloss:0.55121	eval-mlogloss:0.52270
[60]	train-mlogloss:0.54528	eval-mlogloss:0.51627
[61]	train-mlogloss:0.53984	eval-mlogloss:0.51060
[62]	train-mlogloss:0.53491	eval-mlogloss:0.50513
[63]	train-mlogloss:0.53051	eval-mlogloss:0.50059
[64]	train-mlogloss:0.52505	eval-mlogloss:0.49488
[65]	train-mlogloss:0.52047	eval-mlogloss:0.48984
[66]	train-mlogloss:0.51502	eval-mlogloss:0.48403
[67]	train-mlogloss:0.51062	eval-mlogloss:0.47928
[68]	train-mlogloss:0.50606	eval-mlogloss:0.47452
[69]	train-mlogloss:0.50194	eval-mlogloss:0.47001
[70]	train-mlogloss:0.49749	eval-mlogloss:0.46522
[71]	train-mlogloss:0.49420	eval-mlogloss:0.46189
[72]	train-mlogloss:0.48917	eval-mlogloss:0.45684
[73]	train-mlogloss:0.48540	eval-mlogloss:0.45251
[74]	train-mlogloss:0.48086	eval-mlogloss:0.44764
[75]	train-mlogloss:0.47751	eval-mlogloss:0.44416
[76]	train-mlogloss:0.47261	eval-mlogloss:0.43893
[77]	train-mlogloss:0.46848	eval-mlogloss:0.43468
[78]	train-mlogloss:0.46482	eval-mlogloss:0.43104
[79]	train-mlogloss:0.46092	eval-mlogloss:0.42693
[80]	train-mlogloss:0.45800	eval-mlogloss:0.42394
[81]	train-mlogloss:0.45382	eval-mlogloss:0.41964
[82]	train-mlogloss:0.45040	eval-mlogloss:0.41585
[83]	train-mlogloss:0.44648	eval-mlogloss:0.41210
[84]	train-mlogloss:0.44256	eval-mlogloss:0.40804
[85]	train-mlogloss:0.43891	eval-mlogloss:0.40377
[86]	train-mlogloss:0.43558	eval-mlogloss:0.40049
[87]	train-mlogloss:0.43197	eval-mlogloss:0.39666
[88]	train-mlogloss:0.42921	eval-mlogloss:0.39378
[89]	train-mlogloss:0.42521	eval-mlogloss:0.38946
[90]	train-mlogloss:0.42101	eval-mlogloss:0.38472
[91]	train-mlogloss:0.41858	eval-mlogloss:0.38226
[92]	train-mlogloss:0.41515	eval-mlogloss:0.37846
[93]	train-mlogloss:0.41190	eval-mlogloss:0.37500
[94]	train-mlogloss:0.40771	eval-mlogloss:0.37029
[95]	train-mlogloss:0.40440	eval-mlogloss:0.36662
[96]	train-mlogloss:0.40064	eval-mlogloss:0.36238
[97]	train-mlogloss:0.39683	eval-mlogloss:0.35856
[98]	train-mlogloss:0.39416	eval-mlogloss:0.35574
[99]	train-mlogloss:0.39066	eval-mlogloss:0.35185
[100]	train-mlogloss:0.38797	eval-mlogloss:0.34877
[101]	train-mlogloss:0.38440	eval-mlogloss:0.34482
[102]	train-mlogloss:0.38091	eval-mlogloss:0.34092
[103]	train-mlogloss:0.37775	eval-mlogloss:0.33739
[104]	train-mlogloss:0.37447	eval-mlogloss:0.33392
[105]	train-mlogloss:0.37102	eval-mlogloss:0.33026
[106]	train-mlogloss:0.36784	eval-mlogloss:0.32682
[107]	train-mlogloss:0.36468	eval-mlogloss:0.32327
[108]	train-mlogloss:0.36138	eval-mlogloss:0.31981
[109]	train-mlogloss:0.35829	eval-mlogloss:0.31622
[110]	train-mlogloss:0.35595	eval-mlogloss:0.31363
[111]	train-mlogloss:0.35313	eval-mlogloss:0.31029
[112]	train-mlogloss:0.35005	eval-mlogloss:0.30699
[113]	train-mlogloss:0.34787	eval-mlogloss:0.30446
[114]	train-mlogloss:0.34574	eval-mlogloss:0.30224
[115]	train-mlogloss:0.34273	eval-mlogloss:0.29880
[116]	train-mlogloss:0.34022	eval-mlogloss:0.29590
[117]	train-mlogloss:0.33808	eval-mlogloss:0.29361
[118]	train-mlogloss:0.33520	eval-mlogloss:0.29064
[119]	train-mlogloss:0.33262	eval-mlogloss:0.28786
[120]	train-mlogloss:0.32949	eval-mlogloss:0.28435
[121]	train-mlogloss:0.32792	eval-mlogloss:0.28273
[122]	train-mlogloss:0.32584	eval-mlogloss:0.28064
[123]	train-mlogloss:0.32340	eval-mlogloss:0.27791
[124]	train-mlogloss:0.32093	eval-mlogloss:0.27516
[125]	train-mlogloss:0.31866	eval-mlogloss:0.27261
[126]	train-mlogloss:0.31611	eval-mlogloss:0.26961
[127]	train-mlogloss:0.31425	eval-mlogloss:0.26756
[128]	train-mlogloss:0.31168	eval-mlogloss:0.26467
[129]	train-mlogloss:0.31085	eval-mlogloss:0.26357
[130]	train-mlogloss:0.30895	eval-mlogloss:0.26157
[131]	train-mlogloss:0.30737	eval-mlogloss:0.25985
[132]	train-mlogloss:0.30494	eval-mlogloss:0.25708
[133]	train-mlogloss:0.30263	eval-mlogloss:0.25479
[134]	train-mlogloss:0.30104	eval-mlogloss:0.25292
[135]	train-mlogloss:0.29912	eval-mlogloss:0.25073
[136]	train-mlogloss:0.29692	eval-mlogloss:0.24815
[137]	train-mlogloss:0.29530	eval-mlogloss:0.24640
[138]	train-mlogloss:0.29358	eval-mlogloss:0.24455
[139]	train-mlogloss:0.29169	eval-mlogloss:0.24237
[140]	train-mlogloss:0.29045	eval-mlogloss:0.24109
[141]	train-mlogloss:0.28891	eval-mlogloss:0.23926
[142]	train-mlogloss:0.28733	eval-mlogloss:0.23757
[143]	train-mlogloss:0.28557	eval-mlogloss:0.23569
[144]	train-mlogloss:0.28469	eval-mlogloss:0.23496
[145]	train-mlogloss:0.28294	eval-mlogloss:0.23308
[146]	train-mlogloss:0.28117	eval-mlogloss:0.23115
[147]	train-mlogloss:0.27977	eval-mlogloss:0.22955
[148]	train-mlogloss:0.27843	eval-mlogloss:0.22816
[149]	train-mlogloss:0.27761	eval-mlogloss:0.22728
[150]	train-mlogloss:0.27676	eval-mlogloss:0.22633
[151]	train-mlogloss:0.27527	eval-mlogloss:0.22461
[152]	train-mlogloss:0.27427	eval-mlogloss:0.22362
[153]	train-mlogloss:0.27321	eval-mlogloss:0.22240
[154]	train-mlogloss:0.27215	eval-mlogloss:0.22131
[155]	train-mlogloss:0.27064	eval-mlogloss:0.21955
[156]	train-mlogloss:0.26922	eval-mlogloss:0.21795
[157]	train-mlogloss:0.26767	eval-mlogloss:0.21634
[158]	train-mlogloss:0.26650	eval-mlogloss:0.21501
[159]	train-mlogloss:0.26508	eval-mlogloss:0.21335
[160]	train-mlogloss:0.26383	eval-mlogloss:0.21201
[161]	train-mlogloss:0.26194	eval-mlogloss:0.20996
[162]	train-mlogloss:0.26024	eval-mlogloss:0.20797
[163]	train-mlogloss:0.25906	eval-mlogloss:0.20656
[164]	train-mlogloss:0.25774	eval-mlogloss:0.20515
[165]	train-mlogloss:0.25646	eval-mlogloss:0.20361
[166]	train-mlogloss:0.25541	eval-mlogloss:0.20223
[167]	train-mlogloss:0.25398	eval-mlogloss:0.20053
[168]	train-mlogloss:0.25321	eval-mlogloss:0.19971
[169]	train-mlogloss:0.25184	eval-mlogloss:0.19823
[170]	train-mlogloss:0.25070	eval-mlogloss:0.19703
[171]	train-mlogloss:0.24919	eval-mlogloss:0.19531
[172]	train-mlogloss:0.24794	eval-mlogloss:0.19391
[173]	train-mlogloss:0.24636	eval-mlogloss:0.19208
[174]	train-mlogloss:0.24510	eval-mlogloss:0.19059
[175]	train-mlogloss:0.24395	eval-mlogloss:0.18935
[176]	train-mlogloss:0.24307	eval-mlogloss:0.18830
[177]	train-mlogloss:0.24141	eval-mlogloss:0.18645
[178]	train-mlogloss:0.24005	eval-mlogloss:0.18482
[179]	train-mlogloss:0.23916	eval-mlogloss:0.18380
[180]	train-mlogloss:0.23862	eval-mlogloss:0.18306
[181]	train-mlogloss:0.23754	eval-mlogloss:0.18191
[182]	train-mlogloss:0.23630	eval-mlogloss:0.18048
[183]	train-mlogloss:0.23509	eval-mlogloss:0.17902
[184]	train-mlogloss:0.23461	eval-mlogloss:0.17845
[185]	train-mlogloss:0.23357	eval-mlogloss:0.17735
[186]	train-mlogloss:0.23310	eval-mlogloss:0.17676
[187]	train-mlogloss:0.23205	eval-mlogloss:0.17545
[188]	train-mlogloss:0.23121	eval-mlogloss:0.17452
[189]	train-mlogloss:0.22999	eval-mlogloss:0.17320
[190]	train-mlogloss:0.22956	eval-mlogloss:0.17266
[191]	train-mlogloss:0.22942	eval-mlogloss:0.17260
[192]	train-mlogloss:0.22830	eval-mlogloss:0.17128
[193]	train-mlogloss:0.22747	eval-mlogloss:0.17040
[194]	train-mlogloss:0.22690	eval-mlogloss:0.16974
[195]	train-mlogloss:0.22619	eval-mlogloss:0.16890
[196]	train-mlogloss:0.22544	eval-mlogloss:0.16797
[197]	train-mlogloss:0.22496	eval-mlogloss:0.16739
[198]	train-mlogloss:0.22481	eval-mlogloss:0.16718
[199]	train-mlogloss:0.22376	eval-mlogloss:0.16606
[200]	train-mlogloss:0.22293	eval-mlogloss:0.16515
[201]	train-mlogloss:0.22252	eval-mlogloss:0.16461
[202]	train-mlogloss:0.22153	eval-mlogloss:0.16352
[203]	train-mlogloss:0.22073	eval-mlogloss:0.16259
[204]	train-mlogloss:0.21987	eval-mlogloss:0.16160
[205]	train-mlogloss:0.21936	eval-mlogloss:0.16082
[206]	train-mlogloss:0.21910	eval-mlogloss:0.16039
[207]	train-mlogloss:0.21859	eval-mlogloss:0.15981
[208]	train-mlogloss:0.21797	eval-mlogloss:0.15902
[209]	train-mlogloss:0.21730	eval-mlogloss:0.15829
[210]	train-mlogloss:0.21692	eval-mlogloss:0.15778
[211]	train-mlogloss:0.21639	eval-mlogloss:0.15706
[212]	train-mlogloss:0.21630	eval-mlogloss:0.15695
[213]	train-mlogloss:0.21599	eval-mlogloss:0.15659
[214]	train-mlogloss:0.21592	eval-mlogloss:0.15650
[215]	train-mlogloss:0.21563	eval-mlogloss:0.15614
[216]	train-mlogloss:0.21502	eval-mlogloss:0.15554
[217]	train-mlogloss:0.21458	eval-mlogloss:0.15504
[218]	train-mlogloss:0.21434	eval-mlogloss:0.15482
[219]	train-mlogloss:0.21385	eval-mlogloss:0.15424
[220]	train-mlogloss:0.21381	eval-mlogloss:0.15418
[221]	train-mlogloss:0.21351	eval-mlogloss:0.15384
[222]	train-mlogloss:0.21271	eval-mlogloss:0.15285
[223]	train-mlogloss:0.21202	eval-mlogloss:0.15209
[224]	train-mlogloss:0.21171	eval-mlogloss:0.15168
[225]	train-mlogloss:0.21140	eval-mlogloss:0.15129
[226]	train-mlogloss:0.21051	eval-mlogloss:0.15029
[227]	train-mlogloss:0.21032	eval-mlogloss:0.15025
[228]	train-mlogloss:0.20994	eval-mlogloss:0.14978
[229]	train-mlogloss:0.20952	eval-mlogloss:0.14914
[230]	train-mlogloss:0.20946	eval-mlogloss:0.14915
[231]	train-mlogloss:0.20892	eval-mlogloss:0.14849
[232]	train-mlogloss:0.20851	eval-mlogloss:0.14806
[233]	train-mlogloss:0.20808	eval-mlogloss:0.14752
[234]	train-mlogloss:0.20791	eval-mlogloss:0.14723
[235]	train-mlogloss:0.20762	eval-mlogloss:0.14681
[236]	train-mlogloss:0.20731	eval-mlogloss:0.14636
[237]	train-mlogloss:0.20674	eval-mlogloss:0.14556
[238]	train-mlogloss:0.20616	eval-mlogloss:0.14508
[239]	train-mlogloss:0.20617	eval-mlogloss:0.14513
[240]	train-mlogloss:0.20622	eval-mlogloss:0.14514
[241]	train-mlogloss:0.20589	eval-mlogloss:0.14473
[242]	train-mlogloss:0.20575	eval-mlogloss:0.14455
[243]	train-mlogloss:0.20549	eval-mlogloss:0.14417
[244]	train-mlogloss:0.20509	eval-mlogloss:0.14364
[245]	train-mlogloss:0.20507	eval-mlogloss:0.14353
[246]	train-mlogloss:0.20483	eval-mlogloss:0.14319
[247]	train-mlogloss:0.20444	eval-mlogloss:0.14263
[248]	train-mlogloss:0.20443	eval-mlogloss:0.14254
[249]	train-mlogloss:0.20441	eval-mlogloss:0.14257
[250]	train-mlogloss:0.20429	eval-mlogloss:0.14236
[251]	train-mlogloss:0.20424	eval-mlogloss:0.14234
[252]	train-mlogloss:0.20418	eval-mlogloss:0.14223
[253]	train-mlogloss:0.20374	eval-mlogloss:0.14165
[254]	train-mlogloss:0.20371	eval-mlogloss:0.14162
[255]	train-mlogloss:0.20342	eval-mlogloss:0.14124

[I 2026-09-28 23:31:45,015] Trial 26 pruned. Trial was pruned at iteration 256.

[0]	train-mlogloss:1.03964	eval-mlogloss:1.03378

[I 2026-09-28 23:31:45,092] Trial 27 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.08306	eval-mlogloss:1.08479
[1]	train-mlogloss:1.06783	eval-mlogloss:1.06936
[2]	train-mlogloss:1.05286	eval-mlogloss:1.05348
[3]	train-mlogloss:1.04181	eval-mlogloss:1.04099
[4]	train-mlogloss:1.02683	eval-mlogloss:1.02551
[5]	train-mlogloss:1.01203	eval-mlogloss:1.00947
[6]	train-mlogloss:0.99865	eval-mlogloss:0.99477
[7]	train-mlogloss:0.98498	eval-mlogloss:0.98018
[8]	train-mlogloss:0.97237	eval-mlogloss:0.96701
[9]	train-mlogloss:0.96055	eval-mlogloss:0.95479
[10]	train-mlogloss:0.95130	eval-mlogloss:0.94490
[11]	train-mlogloss:0.93853	eval-mlogloss:0.93088
[12]	train-mlogloss:0.92565	eval-mlogloss:0.91695
[13]	train-mlogloss:0.91342	eval-mlogloss:0.90458
[14]	train-mlogloss:0.90146	eval-mlogloss:0.89221
[15]	train-mlogloss:0.88992	eval-mlogloss:0.87981

[I 2026-09-28 23:31:45,969] Trial 28 pruned. Trial was pruned at iteration 16.

[0]	train-mlogloss:1.05836	eval-mlogloss:1.05495
[1]	train-mlogloss:1.02723	eval-mlogloss:1.02180
[2]	train-mlogloss:0.99611	eval-mlogloss:0.99002
[3]	train-mlogloss:0.97251	eval-mlogloss:0.96348

[I 2026-09-28 23:31:46,308] Trial 29 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.06909	eval-mlogloss:1.07106
[1]	train-mlogloss:1.03982	eval-mlogloss:1.04122
[2]	train-mlogloss:1.01089	eval-mlogloss:1.01061
[3]	train-mlogloss:0.98446	eval-mlogloss:0.98287

[I 2026-09-28 23:31:46,465] Trial 30 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.06119	eval-mlogloss:1.05920

[I 2026-09-28 23:31:46,534] Trial 31 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.07896	eval-mlogloss:1.07945
[1]	train-mlogloss:1.05846	eval-mlogloss:1.05865
[2]	train-mlogloss:1.03713	eval-mlogloss:1.03624
[3]	train-mlogloss:1.01916	eval-mlogloss:1.01808

[I 2026-09-28 23:31:46,719] Trial 32 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.07750	eval-mlogloss:1.07905
[1]	train-mlogloss:1.05666	eval-mlogloss:1.05730
[2]	train-mlogloss:1.03513	eval-mlogloss:1.03445
[3]	train-mlogloss:1.01514	eval-mlogloss:1.01334

[I 2026-09-28 23:31:46,921] Trial 33 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.04577	eval-mlogloss:1.04825

[I 2026-09-28 23:31:47,041] Trial 34 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.09104	eval-mlogloss:1.09210
[1]	train-mlogloss:1.08267	eval-mlogloss:1.08396
[2]	train-mlogloss:1.08036	eval-mlogloss:1.08157
[3]	train-mlogloss:1.07524	eval-mlogloss:1.07638
[4]	train-mlogloss:1.06973	eval-mlogloss:1.07209
[5]	train-mlogloss:1.06649	eval-mlogloss:1.06917
[6]	train-mlogloss:1.05896	eval-mlogloss:1.06122
[7]	train-mlogloss:1.05165	eval-mlogloss:1.05253
[8]	train-mlogloss:1.04457	eval-mlogloss:1.04556
[9]	train-mlogloss:1.03654	eval-mlogloss:1.03733
[10]	train-mlogloss:1.03466	eval-mlogloss:1.03561
[11]	train-mlogloss:1.02563	eval-mlogloss:1.02524
[12]	train-mlogloss:1.01932	eval-mlogloss:1.01863
[13]	train-mlogloss:1.01311	eval-mlogloss:1.01200
[14]	train-mlogloss:1.00796	eval-mlogloss:1.00570
[15]	train-mlogloss:1.00297	eval-mlogloss:1.00088
[16]	train-mlogloss:0.99471	eval-mlogloss:0.99209
[17]	train-mlogloss:0.99221	eval-mlogloss:0.98949
[18]	train-mlogloss:0.98584	eval-mlogloss:0.98308
[19]	train-mlogloss:0.98123	eval-mlogloss:0.97848
[20]	train-mlogloss:0.97141	eval-mlogloss:0.96767
[21]	train-mlogloss:0.96803	eval-mlogloss:0.96439
[22]	train-mlogloss:0.96121	eval-mlogloss:0.95681
[23]	train-mlogloss:0.95354	eval-mlogloss:0.94955
[24]	train-mlogloss:0.94539	eval-mlogloss:0.94092
[25]	train-mlogloss:0.93810	eval-mlogloss:0.93337
[26]	train-mlogloss:0.92989	eval-mlogloss:0.92476
[27]	train-mlogloss:0.92143	eval-mlogloss:0.91648
[28]	train-mlogloss:0.91754	eval-mlogloss:0.91237
[29]	train-mlogloss:0.91013	eval-mlogloss:0.90445
[30]	train-mlogloss:0.90406	eval-mlogloss:0.89803
[31]	train-mlogloss:0.89828	eval-mlogloss:0.89112
[32]	train-mlogloss:0.89208	eval-mlogloss:0.88501
[33]	train-mlogloss:0.89006	eval-mlogloss:0.88338
[34]	train-mlogloss:0.88622	eval-mlogloss:0.87874
[35]	train-mlogloss:0.87797	eval-mlogloss:0.86971
[36]	train-mlogloss:0.87373	eval-mlogloss:0.86518
[37]	train-mlogloss:0.86926	eval-mlogloss:0.86046
[38]	train-mlogloss:0.86343	eval-mlogloss:0.85487
[39]	train-mlogloss:0.86015	eval-mlogloss:0.85066
[40]	train-mlogloss:0.85516	eval-mlogloss:0.84521
[41]	train-mlogloss:0.84875	eval-mlogloss:0.83855
[42]	train-mlogloss:0.84369	eval-mlogloss:0.83339
[43]	train-mlogloss:0.84056	eval-mlogloss:0.83077
[44]	train-mlogloss:0.83618	eval-mlogloss:0.82647
[45]	train-mlogloss:0.82992	eval-mlogloss:0.81986
[46]	train-mlogloss:0.82475	eval-mlogloss:0.81429
[47]	train-mlogloss:0.82123	eval-mlogloss:0.81048
[48]	train-mlogloss:0.81994	eval-mlogloss:0.80938
[49]	train-mlogloss:0.81442	eval-mlogloss:0.80358
[50]	train-mlogloss:0.80994	eval-mlogloss:0.79900
[51]	train-mlogloss:0.80635	eval-mlogloss:0.79517
[52]	train-mlogloss:0.79769	eval-mlogloss:0.78597
[53]	train-mlogloss:0.79231	eval-mlogloss:0.78029
[54]	train-mlogloss:0.78802	eval-mlogloss:0.77612
[55]	train-mlogloss:0.78236	eval-mlogloss:0.77012
[56]	train-mlogloss:0.77812	eval-mlogloss:0.76554
[57]	train-mlogloss:0.77551	eval-mlogloss:0.76283
[58]	train-mlogloss:0.77060	eval-mlogloss:0.75723
[59]	train-mlogloss:0.76720	eval-mlogloss:0.75363
[60]	train-mlogloss:0.76061	eval-mlogloss:0.74665
[61]	train-mlogloss:0.75815	eval-mlogloss:0.74411
[62]	train-mlogloss:0.75591	eval-mlogloss:0.74176
[63]	train-mlogloss:0.75112	eval-mlogloss:0.73692
[64]	train-mlogloss:0.75062	eval-mlogloss:0.73628
[65]	train-mlogloss:0.74712	eval-mlogloss:0.73232
[66]	train-mlogloss:0.74451	eval-mlogloss:0.72920
[67]	train-mlogloss:0.74247	eval-mlogloss:0.72684
[68]	train-mlogloss:0.73961	eval-mlogloss:0.72403
[69]	train-mlogloss:0.73784	eval-mlogloss:0.72217
[70]	train-mlogloss:0.73456	eval-mlogloss:0.71915
[71]	train-mlogloss:0.73213	eval-mlogloss:0.71665
[72]	train-mlogloss:0.72602	eval-mlogloss:0.70990
[73]	train-mlogloss:0.72510	eval-mlogloss:0.70849
[74]	train-mlogloss:0.72336	eval-mlogloss:0.70696
[75]	train-mlogloss:0.72158	eval-mlogloss:0.70480
[76]	train-mlogloss:0.71802	eval-mlogloss:0.70071
[77]	train-mlogloss:0.71555	eval-mlogloss:0.69783
[78]	train-mlogloss:0.71501	eval-mlogloss:0.69729
[79]	train-mlogloss:0.71246	eval-mlogloss:0.69466
[80]	train-mlogloss:0.71249	eval-mlogloss:0.69456
[81]	train-mlogloss:0.71131	eval-mlogloss:0.69390
[82]	train-mlogloss:0.70863	eval-mlogloss:0.69123
[83]	train-mlogloss:0.70376	eval-mlogloss:0.68568
[84]	train-mlogloss:0.70377	eval-mlogloss:0.68560
[85]	train-mlogloss:0.70227	eval-mlogloss:0.68475
[86]	train-mlogloss:0.69810	eval-mlogloss:0.68005
[87]	train-mlogloss:0.69766	eval-mlogloss:0.67972
[88]	train-mlogloss:0.69666	eval-mlogloss:0.67870
[89]	train-mlogloss:0.69361	eval-mlogloss:0.67566
[90]	train-mlogloss:0.69080	eval-mlogloss:0.67269
[91]	train-mlogloss:0.68996	eval-mlogloss:0.67164
[92]	train-mlogloss:0.68549	eval-mlogloss:0.66652
[93]	train-mlogloss:0.68216	eval-mlogloss:0.66318
[94]	train-mlogloss:0.68041	eval-mlogloss:0.66133
[95]	train-mlogloss:0.67899	eval-mlogloss:0.65991
[96]	train-mlogloss:0.67489	eval-mlogloss:0.65522
[97]	train-mlogloss:0.67066	eval-mlogloss:0.65137
[98]	train-mlogloss:0.66890	eval-mlogloss:0.64974
[99]	train-mlogloss:0.66708	eval-mlogloss:0.64761
[100]	train-mlogloss:0.66442	eval-mlogloss:0.64507
[101]	train-mlogloss:0.66309	eval-mlogloss:0.64424
[102]	train-mlogloss:0.66255	eval-mlogloss:0.64369
[103]	train-mlogloss:0.66176	eval-mlogloss:0.64308
[104]	train-mlogloss:0.65930	eval-mlogloss:0.64038
[105]	train-mlogloss:0.65505	eval-mlogloss:0.63602
[106]	train-mlogloss:0.65505	eval-mlogloss:0.63604
[107]	train-mlogloss:0.65288	eval-mlogloss:0.63357
[108]	train-mlogloss:0.65143	eval-mlogloss:0.63204
[109]	train-mlogloss:0.64968	eval-mlogloss:0.63025
[110]	train-mlogloss:0.64915	eval-mlogloss:0.62934
[111]	train-mlogloss:0.64746	eval-mlogloss:0.62714
[112]	train-mlogloss:0.64620	eval-mlogloss:0.62574
[113]	train-mlogloss:0.64315	eval-mlogloss:0.62199
[114]	train-mlogloss:0.64064	eval-mlogloss:0.61967
[115]	train-mlogloss:0.63805	eval-mlogloss:0.61666
[116]	train-mlogloss:0.63525	eval-mlogloss:0.61430
[117]	train-mlogloss:0.63130	eval-mlogloss:0.60949
[118]	train-mlogloss:0.62687	eval-mlogloss:0.60488
[119]	train-mlogloss:0.62555	eval-mlogloss:0.60356
[120]	train-mlogloss:0.62534	eval-mlogloss:0.60333
[121]	train-mlogloss:0.62422	eval-mlogloss:0.60211
[122]	train-mlogloss:0.62234	eval-mlogloss:0.60012
[123]	train-mlogloss:0.62200	eval-mlogloss:0.59975
[124]	train-mlogloss:0.61986	eval-mlogloss:0.59766
[125]	train-mlogloss:0.61959	eval-mlogloss:0.59732
[126]	train-mlogloss:0.61789	eval-mlogloss:0.59543
[127]	train-mlogloss:0.61733	eval-mlogloss:0.59466
[128]	train-mlogloss:0.61695	eval-mlogloss:0.59408
[129]	train-mlogloss:0.61694	eval-mlogloss:0.59408
[130]	train-mlogloss:0.61274	eval-mlogloss:0.58937
[131]	train-mlogloss:0.61236	eval-mlogloss:0.58857
[132]	train-mlogloss:0.60997	eval-mlogloss:0.58591
[133]	train-mlogloss:0.60786	eval-mlogloss:0.58391
[134]	train-mlogloss:0.60757	eval-mlogloss:0.58355
[135]	train-mlogloss:0.60514	eval-mlogloss:0.58071
[136]	train-mlogloss:0.60292	eval-mlogloss:0.57830
[137]	train-mlogloss:0.59904	eval-mlogloss:0.57445
[138]	train-mlogloss:0.59589	eval-mlogloss:0.57102
[139]	train-mlogloss:0.59523	eval-mlogloss:0.57022
[140]	train-mlogloss:0.59213	eval-mlogloss:0.56643
[141]	train-mlogloss:0.59187	eval-mlogloss:0.56587
[142]	train-mlogloss:0.59043	eval-mlogloss:0.56446
[143]	train-mlogloss:0.58993	eval-mlogloss:0.56366
[144]	train-mlogloss:0.58874	eval-mlogloss:0.56232
[145]	train-mlogloss:0.58862	eval-mlogloss:0.56243
[146]	train-mlogloss:0.58588	eval-mlogloss:0.55934
[147]	train-mlogloss:0.58536	eval-mlogloss:0.55890
[148]	train-mlogloss:0.58488	eval-mlogloss:0.55815
[149]	train-mlogloss:0.58471	eval-mlogloss:0.55781
[150]	train-mlogloss:0.58458	eval-mlogloss:0.55787
[151]	train-mlogloss:0.58279	eval-mlogloss:0.55610
[152]	train-mlogloss:0.58041	eval-mlogloss:0.55326
[153]	train-mlogloss:0.57825	eval-mlogloss:0.55085
[154]	train-mlogloss:0.57786	eval-mlogloss:0.55025
[155]	train-mlogloss:0.57650	eval-mlogloss:0.54880
[156]	train-mlogloss:0.57595	eval-mlogloss:0.54805
[157]	train-mlogloss:0.57551	eval-mlogloss:0.54744
[158]	train-mlogloss:0.57526	eval-mlogloss:0.54721
[159]	train-mlogloss:0.57307	eval-mlogloss:0.54434
[160]	train-mlogloss:0.57307	eval-mlogloss:0.54430
[161]	train-mlogloss:0.57194	eval-mlogloss:0.54256
[162]	train-mlogloss:0.57164	eval-mlogloss:0.54192
[163]	train-mlogloss:0.57137	eval-mlogloss:0.54167
[164]	train-mlogloss:0.56959	eval-mlogloss:0.53987
[165]	train-mlogloss:0.56761	eval-mlogloss:0.53740
[166]	train-mlogloss:0.56761	eval-mlogloss:0.53745
[167]	train-mlogloss:0.56661	eval-mlogloss:0.53645
[168]	train-mlogloss:0.56661	eval-mlogloss:0.53643
[169]	train-mlogloss:0.56661	eval-mlogloss:0.53643
[170]	train-mlogloss:0.56311	eval-mlogloss:0.53267
[171]	train-mlogloss:0.56257	eval-mlogloss:0.53192
[172]	train-mlogloss:0.56131	eval-mlogloss:0.53051
[173]	train-mlogloss:0.56120	eval-mlogloss:0.53036
[174]	train-mlogloss:0.55935	eval-mlogloss:0.52829
[175]	train-mlogloss:0.55890	eval-mlogloss:0.52782
[176]	train-mlogloss:0.55875	eval-mlogloss:0.52763
[177]	train-mlogloss:0.55875	eval-mlogloss:0.52760
[178]	train-mlogloss:0.55662	eval-mlogloss:0.52509
[179]	train-mlogloss:0.55566	eval-mlogloss:0.52385
[180]	train-mlogloss:0.55566	eval-mlogloss:0.52385
[181]	train-mlogloss:0.55568	eval-mlogloss:0.52371
[182]	train-mlogloss:0.55397	eval-mlogloss:0.52191
[183]	train-mlogloss:0.55253	eval-mlogloss:0.52035
[184]	train-mlogloss:0.55225	eval-mlogloss:0.51983
[185]	train-mlogloss:0.55226	eval-mlogloss:0.51978
[186]	train-mlogloss:0.55227	eval-mlogloss:0.51977
[187]	train-mlogloss:0.55226	eval-mlogloss:0.51975
[188]	train-mlogloss:0.55112	eval-mlogloss:0.51893
[189]	train-mlogloss:0.55077	eval-mlogloss:0.51810
[190]	train-mlogloss:0.55054	eval-mlogloss:0.51802
[191]	train-mlogloss:0.55055	eval-mlogloss:0.51803
[192]	train-mlogloss:0.54990	eval-mlogloss:0.51721
[193]	train-mlogloss:0.54976	eval-mlogloss:0.51703
[194]	train-mlogloss:0.54948	eval-mlogloss:0.51684
[195]	train-mlogloss:0.54886	eval-mlogloss:0.51619
[196]	train-mlogloss:0.54787	eval-mlogloss:0.51514
[197]	train-mlogloss:0.54787	eval-mlogloss:0.51517
[198]	train-mlogloss:0.54751	eval-mlogloss:0.51449
[199]	train-mlogloss:0.54649	eval-mlogloss:0.51351
[200]	train-mlogloss:0.54633	eval-mlogloss:0.51338
[201]	train-mlogloss:0.54564	eval-mlogloss:0.51247
[202]	train-mlogloss:0.54475	eval-mlogloss:0.51158
[203]	train-mlogloss:0.54459	eval-mlogloss:0.51117
[204]	train-mlogloss:0.54451	eval-mlogloss:0.51114
[205]	train-mlogloss:0.54241	eval-mlogloss:0.50856
[206]	train-mlogloss:0.54220	eval-mlogloss:0.50825
[207]	train-mlogloss:0.54032	eval-mlogloss:0.50613
[208]	train-mlogloss:0.54004	eval-mlogloss:0.50592
[209]	train-mlogloss:0.54003	eval-mlogloss:0.50590
[210]	train-mlogloss:0.54004	eval-mlogloss:0.50596
[211]	train-mlogloss:0.54003	eval-mlogloss:0.50596
[212]	train-mlogloss:0.53996	eval-mlogloss:0.50597
[213]	train-mlogloss:0.53847	eval-mlogloss:0.50416
[214]	train-mlogloss:0.53847	eval-mlogloss:0.50418
[215]	train-mlogloss:0.53847	eval-mlogloss:0.50417
[216]	train-mlogloss:0.53847	eval-mlogloss:0.50417
[217]	train-mlogloss:0.53840	eval-mlogloss:0.50427
[218]	train-mlogloss:0.53668	eval-mlogloss:0.50254
[219]	train-mlogloss:0.53480	eval-mlogloss:0.50041
[220]	train-mlogloss:0.53481	eval-mlogloss:0.50042
[221]	train-mlogloss:0.53374	eval-mlogloss:0.49950
[222]	train-mlogloss:0.53372	eval-mlogloss:0.49953
[223]	train-mlogloss:0.53110	eval-mlogloss:0.49674
[224]	train-mlogloss:0.53112	eval-mlogloss:0.49674
[225]	train-mlogloss:0.53112	eval-mlogloss:0.49671
[226]	train-mlogloss:0.52922	eval-mlogloss:0.49467
[227]	train-mlogloss:0.52921	eval-mlogloss:0.49466
[228]	train-mlogloss:0.52767	eval-mlogloss:0.49261
[229]	train-mlogloss:0.52592	eval-mlogloss:0.49055
[230]	train-mlogloss:0.52536	eval-mlogloss:0.48977
[231]	train-mlogloss:0.52525	eval-mlogloss:0.48968
[232]	train-mlogloss:0.52523	eval-mlogloss:0.48976
[233]	train-mlogloss:0.52516	eval-mlogloss:0.48962
[234]	train-mlogloss:0.52515	eval-mlogloss:0.48969
[235]	train-mlogloss:0.52515	eval-mlogloss:0.48967
[236]	train-mlogloss:0.52396	eval-mlogloss:0.48838
[237]	train-mlogloss:0.52192	eval-mlogloss:0.48608
[238]	train-mlogloss:0.52090	eval-mlogloss:0.48527
[239]	train-mlogloss:0.52092	eval-mlogloss:0.48521
[240]	train-mlogloss:0.52093	eval-mlogloss:0.48517
[241]	train-mlogloss:0.51944	eval-mlogloss:0.48316
[242]	train-mlogloss:0.51910	eval-mlogloss:0.48262
[243]	train-mlogloss:0.51763	eval-mlogloss:0.48099
[244]	train-mlogloss:0.51761	eval-mlogloss:0.48103
[245]	train-mlogloss:0.51759	eval-mlogloss:0.48110
[246]	train-mlogloss:0.51747	eval-mlogloss:0.48104
[247]	train-mlogloss:0.51746	eval-mlogloss:0.48103
[248]	train-mlogloss:0.51718	eval-mlogloss:0.48070
[249]	train-mlogloss:0.51718	eval-mlogloss:0.48070
[250]	train-mlogloss:0.51703	eval-mlogloss:0.48050
[251]	train-mlogloss:0.51702	eval-mlogloss:0.48052
[252]	train-mlogloss:0.51703	eval-mlogloss:0.48047
[253]	train-mlogloss:0.51706	eval-mlogloss:0.48040
[254]	train-mlogloss:0.51707	eval-mlogloss:0.48040
[255]	train-mlogloss:0.51709	eval-mlogloss:0.48035
[256]	train-mlogloss:0.51709	eval-mlogloss:0.48035
[257]	train-mlogloss:0.51687	eval-mlogloss:0.48016
[258]	train-mlogloss:0.51663	eval-mlogloss:0.47996
[259]	train-mlogloss:0.51663	eval-mlogloss:0.47997
[260]	train-mlogloss:0.51641	eval-mlogloss:0.47990
[261]	train-mlogloss:0.51627	eval-mlogloss:0.47978
[262]	train-mlogloss:0.51594	eval-mlogloss:0.47906
[263]	train-mlogloss:0.51554	eval-mlogloss:0.47882
[264]	train-mlogloss:0.51554	eval-mlogloss:0.47883
[265]	train-mlogloss:0.51420	eval-mlogloss:0.47738
[266]	train-mlogloss:0.51420	eval-mlogloss:0.47740
[267]	train-mlogloss:0.51397	eval-mlogloss:0.47703
[268]	train-mlogloss:0.51361	eval-mlogloss:0.47649
[269]	train-mlogloss:0.51359	eval-mlogloss:0.47655
[270]	train-mlogloss:0.51192	eval-mlogloss:0.47424
[271]	train-mlogloss:0.51190	eval-mlogloss:0.47430
[272]	train-mlogloss:0.51191	eval-mlogloss:0.47426
[273]	train-mlogloss:0.51183	eval-mlogloss:0.47428
[274]	train-mlogloss:0.51183	eval-mlogloss:0.47428
[275]	train-mlogloss:0.50873	eval-mlogloss:0.47108
[276]	train-mlogloss:0.50875	eval-mlogloss:0.47103
[277]	train-mlogloss:0.50874	eval-mlogloss:0.47102
[278]	train-mlogloss:0.50876	eval-mlogloss:0.47095
[279]	train-mlogloss:0.50875	eval-mlogloss:0.47096
[280]	train-mlogloss:0.50873	eval-mlogloss:0.47102
[281]	train-mlogloss:0.50874	eval-mlogloss:0.47100
[282]	train-mlogloss:0.50874	eval-mlogloss:0.47098
[283]	train-mlogloss:0.50867	eval-mlogloss:0.47087
[284]	train-mlogloss:0.50789	eval-mlogloss:0.47018
[285]	train-mlogloss:0.50789	eval-mlogloss:0.47019
[286]	train-mlogloss:0.50790	eval-mlogloss:0.47019
[287]	train-mlogloss:0.50789	eval-mlogloss:0.47022
[288]	train-mlogloss:0.50788	eval-mlogloss:0.47024
[289]	train-mlogloss:0.50787	eval-mlogloss:0.47024
[290]	train-mlogloss:0.50760	eval-mlogloss:0.46983
[291]	train-mlogloss:0.50746	eval-mlogloss:0.46975
[292]	train-mlogloss:0.50708	eval-mlogloss:0.46891
[293]	train-mlogloss:0.50709	eval-mlogloss:0.46887
[294]	train-mlogloss:0.50708	eval-mlogloss:0.46890
[295]	train-mlogloss:0.50698	eval-mlogloss:0.46880
[296]	train-mlogloss:0.50696	eval-mlogloss:0.46888
[297]	train-mlogloss:0.50677	eval-mlogloss:0.46846
[298]	train-mlogloss:0.50676	eval-mlogloss:0.46849
[299]	train-mlogloss:0.50621	eval-mlogloss:0.46755

[I 2026-09-28 23:31:53,887] Trial 35 finished with value: 0.9666666666666667 and parameters: {'lambda': 0.25588398610912994, 'alpha': 0.0005260575136374047, 'eta': 0.012611328290245279, 'gamma': 0.4504068976147915, 'max_depth': 9, 'min_child_weight': 9, 'subsample': 0.42543742188689104, 'colsample_bytree': 0.48259152530475957}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.00162	eval-mlogloss:0.99949

[I 2026-09-28 23:31:53,970] Trial 36 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.06604	eval-mlogloss:1.06615

[I 2026-09-28 23:31:54,038] Trial 37 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.06953	eval-mlogloss:1.06837

[I 2026-09-28 23:31:54,102] Trial 38 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03356	eval-mlogloss:1.03524

[I 2026-09-28 23:31:54,172] Trial 39 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.05261	eval-mlogloss:1.05411

[I 2026-09-28 23:31:54,250] Trial 40 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.05424	eval-mlogloss:1.05665

[I 2026-09-28 23:31:54,314] Trial 41 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.08822	eval-mlogloss:1.08996
[1]	train-mlogloss:1.07957	eval-mlogloss:1.08117
[2]	train-mlogloss:1.07056	eval-mlogloss:1.07163
[3]	train-mlogloss:1.06342	eval-mlogloss:1.06434
[4]	train-mlogloss:1.05391	eval-mlogloss:1.05502
[5]	train-mlogloss:1.04634	eval-mlogloss:1.04737
[6]	train-mlogloss:1.03794	eval-mlogloss:1.03876
[7]	train-mlogloss:1.02669	eval-mlogloss:1.02613
[8]	train-mlogloss:1.01611	eval-mlogloss:1.01577
[9]	train-mlogloss:1.00638	eval-mlogloss:1.00546
[10]	train-mlogloss:0.99813	eval-mlogloss:0.99672
[11]	train-mlogloss:0.98928	eval-mlogloss:0.98675
[12]	train-mlogloss:0.97796	eval-mlogloss:0.97461
[13]	train-mlogloss:0.96989	eval-mlogloss:0.96588
[14]	train-mlogloss:0.95977	eval-mlogloss:0.95580
[15]	train-mlogloss:0.95093	eval-mlogloss:0.94743
[16]	train-mlogloss:0.94045	eval-mlogloss:0.93694
[17]	train-mlogloss:0.93491	eval-mlogloss:0.93149
[18]	train-mlogloss:0.92601	eval-mlogloss:0.92289
[19]	train-mlogloss:0.91877	eval-mlogloss:0.91539
[20]	train-mlogloss:0.90812	eval-mlogloss:0.90396
[21]	train-mlogloss:0.90030	eval-mlogloss:0.89599
[22]	train-mlogloss:0.89282	eval-mlogloss:0.88778
[23]	train-mlogloss:0.88567	eval-mlogloss:0.88091
[24]	train-mlogloss:0.87755	eval-mlogloss:0.87153
[25]	train-mlogloss:0.87085	eval-mlogloss:0.86508
[26]	train-mlogloss:0.86302	eval-mlogloss:0.85673
[27]	train-mlogloss:0.85509	eval-mlogloss:0.84891
[28]	train-mlogloss:0.84829	eval-mlogloss:0.84162
[29]	train-mlogloss:0.84170	eval-mlogloss:0.83466
[30]	train-mlogloss:0.83553	eval-mlogloss:0.82818
[31]	train-mlogloss:0.83222	eval-mlogloss:0.82450
[32]	train-mlogloss:0.82773	eval-mlogloss:0.81989
[33]	train-mlogloss:0.82329	eval-mlogloss:0.81520
[34]	train-mlogloss:0.81822	eval-mlogloss:0.80942
[35]	train-mlogloss:0.81075	eval-mlogloss:0.80144
[36]	train-mlogloss:0.80678	eval-mlogloss:0.79724
[37]	train-mlogloss:0.79836	eval-mlogloss:0.78838
[38]	train-mlogloss:0.79200	eval-mlogloss:0.78143
[39]	train-mlogloss:0.78668	eval-mlogloss:0.77619
[40]	train-mlogloss:0.78155	eval-mlogloss:0.77119
[41]	train-mlogloss:0.77838	eval-mlogloss:0.76784
[42]	train-mlogloss:0.77289	eval-mlogloss:0.76185
[43]	train-mlogloss:0.76618	eval-mlogloss:0.75380
[44]	train-mlogloss:0.76029	eval-mlogloss:0.74835
[45]	train-mlogloss:0.75454	eval-mlogloss:0.74233
[46]	train-mlogloss:0.74785	eval-mlogloss:0.73443
[47]	train-mlogloss:0.74436	eval-mlogloss:0.72997
[48]	train-mlogloss:0.74344	eval-mlogloss:0.72945
[49]	train-mlogloss:0.73890	eval-mlogloss:0.72470
[50]	train-mlogloss:0.73289	eval-mlogloss:0.71848
[51]	train-mlogloss:0.72974	eval-mlogloss:0.71508
[52]	train-mlogloss:0.72439	eval-mlogloss:0.70949
[53]	train-mlogloss:0.71790	eval-mlogloss:0.70279
[54]	train-mlogloss:0.71128	eval-mlogloss:0.69598
[55]	train-mlogloss:0.70816	eval-mlogloss:0.69255
[56]	train-mlogloss:0.70473	eval-mlogloss:0.68921
[57]	train-mlogloss:0.70192	eval-mlogloss:0.68622
[58]	train-mlogloss:0.69640	eval-mlogloss:0.68041
[59]	train-mlogloss:0.69245	eval-mlogloss:0.67633
[60]	train-mlogloss:0.68712	eval-mlogloss:0.67075
[61]	train-mlogloss:0.68702	eval-mlogloss:0.67067
[62]	train-mlogloss:0.68412	eval-mlogloss:0.66733
[63]	train-mlogloss:0.68213	eval-mlogloss:0.66527

[I 2026-09-28 23:31:55,417] Trial 42 pruned. Trial was pruned at iteration 64.

[0]	train-mlogloss:1.05774	eval-mlogloss:1.05437

[I 2026-09-28 23:31:55,487] Trial 43 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03446	eval-mlogloss:1.03428

[I 2026-09-28 23:31:55,562] Trial 44 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.06742	eval-mlogloss:1.06597

[I 2026-09-28 23:31:55,635] Trial 45 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.08510	eval-mlogloss:1.08743
[1]	train-mlogloss:1.06951	eval-mlogloss:1.07126
[2]	train-mlogloss:1.06201	eval-mlogloss:1.06397
[3]	train-mlogloss:1.05450	eval-mlogloss:1.05654
[4]	train-mlogloss:1.04210	eval-mlogloss:1.04432
[5]	train-mlogloss:1.03482	eval-mlogloss:1.03704
[6]	train-mlogloss:1.02287	eval-mlogloss:1.02478
[7]	train-mlogloss:1.01513	eval-mlogloss:1.01649
[8]	train-mlogloss:1.00501	eval-mlogloss:1.00660
[9]	train-mlogloss:0.99300	eval-mlogloss:0.99482
[10]	train-mlogloss:0.98976	eval-mlogloss:0.99145
[11]	train-mlogloss:0.97860	eval-mlogloss:0.97950
[12]	train-mlogloss:0.97210	eval-mlogloss:0.97288
[13]	train-mlogloss:0.96423	eval-mlogloss:0.96502
[14]	train-mlogloss:0.95790	eval-mlogloss:0.95822
[15]	train-mlogloss:0.95019	eval-mlogloss:0.95078
[16]	train-mlogloss:0.94188	eval-mlogloss:0.94251
[17]	train-mlogloss:0.93772	eval-mlogloss:0.93856
[18]	train-mlogloss:0.93022	eval-mlogloss:0.93049
[19]	train-mlogloss:0.92390	eval-mlogloss:0.92378
[20]	train-mlogloss:0.91397	eval-mlogloss:0.91267
[21]	train-mlogloss:0.90646	eval-mlogloss:0.90510
[22]	train-mlogloss:0.89780	eval-mlogloss:0.89571
[23]	train-mlogloss:0.88621	eval-mlogloss:0.88410
[24]	train-mlogloss:0.87456	eval-mlogloss:0.87165
[25]	train-mlogloss:0.86564	eval-mlogloss:0.86256
[26]	train-mlogloss:0.85376	eval-mlogloss:0.84975
[27]	train-mlogloss:0.84166	eval-mlogloss:0.83688
[28]	train-mlogloss:0.83406	eval-mlogloss:0.82888
[29]	train-mlogloss:0.82568	eval-mlogloss:0.82008
[30]	train-mlogloss:0.81931	eval-mlogloss:0.81298
[31]	train-mlogloss:0.81268	eval-mlogloss:0.80540
[32]	train-mlogloss:0.80657	eval-mlogloss:0.79866
[33]	train-mlogloss:0.80056	eval-mlogloss:0.79278
[34]	train-mlogloss:0.79613	eval-mlogloss:0.78759
[35]	train-mlogloss:0.78858	eval-mlogloss:0.77955
[36]	train-mlogloss:0.78300	eval-mlogloss:0.77419
[37]	train-mlogloss:0.77838	eval-mlogloss:0.76992
[38]	train-mlogloss:0.77216	eval-mlogloss:0.76344
[39]	train-mlogloss:0.76535	eval-mlogloss:0.75623
[40]	train-mlogloss:0.75845	eval-mlogloss:0.74863
[41]	train-mlogloss:0.75108	eval-mlogloss:0.74037
[42]	train-mlogloss:0.74268	eval-mlogloss:0.73131
[43]	train-mlogloss:0.73987	eval-mlogloss:0.72895
[44]	train-mlogloss:0.73471	eval-mlogloss:0.72378
[45]	train-mlogloss:0.72911	eval-mlogloss:0.71786
[46]	train-mlogloss:0.72120	eval-mlogloss:0.70930
[47]	train-mlogloss:0.71406	eval-mlogloss:0.70203
[48]	train-mlogloss:0.70584	eval-mlogloss:0.69333
[49]	train-mlogloss:0.69697	eval-mlogloss:0.68344
[50]	train-mlogloss:0.69067	eval-mlogloss:0.67708
[51]	train-mlogloss:0.68681	eval-mlogloss:0.67295
[52]	train-mlogloss:0.67836	eval-mlogloss:0.66415
[53]	train-mlogloss:0.67181	eval-mlogloss:0.65749
[54]	train-mlogloss:0.66817	eval-mlogloss:0.65387
[55]	train-mlogloss:0.66245	eval-mlogloss:0.64728
[56]	train-mlogloss:0.65610	eval-mlogloss:0.64092
[57]	train-mlogloss:0.65152	eval-mlogloss:0.63632
[58]	train-mlogloss:0.64645	eval-mlogloss:0.63049
[59]	train-mlogloss:0.64126	eval-mlogloss:0.62487
[60]	train-mlogloss:0.63452	eval-mlogloss:0.61699
[61]	train-mlogloss:0.63060	eval-mlogloss:0.61269
[62]	train-mlogloss:0.62691	eval-mlogloss:0.60855
[63]	train-mlogloss:0.62143	eval-mlogloss:0.60275

[I 2026-09-28 23:31:56,456] Trial 46 pruned. Trial was pruned at iteration 64.

[0]	train-mlogloss:1.06669	eval-mlogloss:1.06467

[I 2026-09-28 23:31:56,520] Trial 47 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.04123	eval-mlogloss:1.04144

[I 2026-09-28 23:31:56,580] Trial 48 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.07088	eval-mlogloss:1.07190
[1]	train-mlogloss:1.03941	eval-mlogloss:1.03906
[2]	train-mlogloss:1.03166	eval-mlogloss:1.03258
[3]	train-mlogloss:1.01627	eval-mlogloss:1.01485

[I 2026-09-28 23:31:56,708] Trial 49 pruned. Trial was pruned at iteration 4.

Best trial: {'lambda': 4.1337559910672894e-05, 'alpha': 0.011808853729328387, 'eta': 0.24005561243597381, 'gamma': 0.011928557488665113, 'max_depth': 9, 'min_child_weight': 1, 'subsample': 0.7798325311658101, 'colsample_bytree': 0.7619585418840047}
Best accuracy: 1.0

In [38]:
from optuna.visualization import plot_intermediate_values

# 1. Plot intermediate values during the trials
plot_intermediate_values(study).show()